# -*- coding: utf-8 -*-
"""Object_Detection_FasterCNN_DVC_TensorBoard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-V4vAze-cEON8hdxIvWwTIOmFZZHb-OA

# Guns Object Detection - Faster R-CNN + DVC + MLflow (DagsHub)

**Dataset:** [Kaggle - issaisasank/guns-object-detection](https://www.kaggle.com/datasets/issaisasank/guns-object-detection)  
**Model:** Faster R-CNN ResNet-50 FPN (fine-tuned, 2 classes: background + gun)  
**Tracking:** MLflow -> DagsHub  
**Pipeline:** DVC stages (data_ingestion -> model_training)  
**Logging:** TensorBoard + rotating file logs  

### Notebook Flow
1. Install dependencies & set environment variables  
2. Set up project directory structure  
3. Write all source modules (logger, exceptions, config, data ingestion, dataset, model)  
4. Run DVC pipeline (data_ingestion -> model_training)  
5. View TensorBoard logs  
6. Verify artifacts and MLflow runs  

> **GPU:** Enable *Runtime -> Change runtime type -> T4 GPU* before running.  
> **Secrets:** Add `MONGO_DB_URL`, `MLFLOW_TRACKING_URI`, `MLFLOW_TRACKING_USERNAME`, `MLFLOW_TRACKING_PASSWORD`, `KAGGLE_USERNAME`, `KAGGLE_KEY` in Secrets (lock icon on left panel).
"""

# ============================================================
# CELL 1: Install all required packages
# torch/torchvision are pre-installed on Colab GPU runtimes.
# dvc   -> pipeline orchestration
# mlflow -> experiment tracking (logs to DagsHub)
# kagglehub -> authenticated Kaggle dataset downloads
# ============================================================

!pip install -q \
    kagglehub \
    dvc \
    mlflow \
    dagshub \
    pymongo \
    tqdm \
    opencv-python-headless \
    tensorboard

print("All packages installed successfully.")

# ============================================================
# CELL 2: Set environment variables from Colab Secrets
# All sensitive credentials are pulled from Colab's Secrets
# vault (lock icon on the left panel).
# Never hard-code credentials in notebooks.
# ============================================================

import os
from google.colab import userdata

# MongoDB (optional - used for metadata storage)
os.environ['MONGO_DB_URL'] = userdata.get('MONGO_DB_URL')

# Kaggle API credentials (needed by kagglehub for dataset download)
os.environ['KAGGLE_USERNAME'] = userdata.get('KAGGLE_USERNAME')
os.environ['KAGGLE_KEY']      = userdata.get('KAGGLE_KEY')

# MLflow / DagsHub experiment tracking
USE_DAGSHUB = True  # Set False to log locally inside Colab instead

if USE_DAGSHUB:
    # Remote tracking: experiments appear on your DagsHub project page
    os.environ['MLFLOW_TRACKING_URI']      = userdata.get('MLFLOW_TRACKING_URI')
    os.environ['MLFLOW_TRACKING_USERNAME'] = userdata.get('MLFLOW_TRACKING_USERNAME')
    os.environ['MLFLOW_TRACKING_PASSWORD'] = userdata.get('MLFLOW_TRACKING_PASSWORD')
else:
    # Local fallback: mlruns/ folder in the current working directory
    os.environ['MLFLOW_TRACKING_URI'] = f"file://{os.getcwd()}/mlruns"

print('Env vars set.')
print(f"   MLFLOW_TRACKING_URI = {os.environ['MLFLOW_TRACKING_URI']}")

# ============================================================
# CELL 3: Create project directory structure
# Mirrors the original project layout so DVC paths resolve.
#
#  /content/guns_detection/
#  |-- src/            <- Python modules (written in subsequent cells)
#  |-- config/         <- Configuration constants
#  |-- artifacts/
#  |   |-- raw/        <- DVC output: Images/ + Labels/
#  |   `-- models/     <- DVC output: fasterrcnn.pth
#  |-- logs/           <- Rotating log files
#  |-- tensorboard_logs/
#  |-- mlruns/         <- Local MLflow (only when USE_DAGSHUB=False)
#  `-- dvc.yaml        <- DVC pipeline definition
# ============================================================

import os, pathlib

PROJECT_ROOT = pathlib.Path("/content/guns_detection")

dirs = [
    "src", "config",
    "artifacts/raw/Images", "artifacts/raw/Labels",
    "artifacts/models",
    "logs",
    "tensorboard_logs",
    "mlruns",
]

for d in dirs:
    (PROJECT_ROOT / d).mkdir(parents=True, exist_ok=True)

# Change into the project root so all relative paths work
os.chdir(PROJECT_ROOT)
print(f"Project root: {PROJECT_ROOT}")
print("Directory tree:")
for p in sorted(PROJECT_ROOT.rglob("*")):
    if ".git" not in str(p):
        print(" ", p.relative_to(PROJECT_ROOT))

# ============================================================
# CELL 4: Create __init__.py so Python treats folders as packages
# ============================================================

for pkg in ["src", "config"]:
    init = PROJECT_ROOT / pkg / "__init__.py"
    init.write_text("")
print("__init__.py files created.")

import textwrap
import pathlib

PROJECT_ROOT = pathlib.Path("/content/guns_detection") # Ensuring PROJECT_ROOT is defined for this cell's context if run independently

raw_logger_code = """
    import os
    import logging
    from datetime import datetime

    LOGS_DIR = "logs"
    os.makedirs(LOGS_DIR, exist_ok=True)

    # Each run gets a unique log file (never overwrites previous runs)
    LOG_FILE = os.path.join(
        LOGS_DIR,
        f"log_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.log"
    )

    logging.basicConfig(
        filename=LOG_FILE,
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
        level=logging.INFO,
    )

    # Stream to stdout so Colab output shows log lines in real-time
    _console = logging.StreamHandler()
    _console.setLevel(logging.INFO)
    _console.setFormatter(
        logging.Formatter("%(asctime)s - %(levelname)s - %(name)s - %(message)s")
    )
    logging.getLogger("").addHandler(_console)


    def get_logger(name: str) -> logging.Logger:
        '''Return a named logger; all loggers inherit the root configuration.'''
        logger = logging.getLogger(name)
        logger.setLevel(logging.INFO)
        return logger
"""
logger_code = textwrap.dedent(raw_logger_code)

(PROJECT_ROOT / "src" / "logger.py").write_text(logger_code)
print("src/logger.py written.")

# ============================================================
# CELL 6: Write src/custom_exception.py
# Wraps any caught exception with file name + line number
# for easier debugging in DVC pipeline runs.
# ============================================================

import textwrap

exception_code = """
import sys


class CustomException(Exception):
    '''
    Enriches standard Python exceptions with the exact file and line
    number where the original error was raised. Pass the caught
    exception as `error_detail` so the traceback can be inspected.
    '''

    def __init__(self, message: str, error_detail: Exception = None):
        self.error_message = self._build_message(message, error_detail)
        super().__init__(self.error_message)

    @staticmethod
    def _build_message(message: str, error_detail: Exception) -> str:
        if error_detail is not None:
            # Walk to the innermost frame of the traceback
            tb = error_detail.__traceback__
            while tb and tb.tb_next:
                tb = tb.tb_next
            file_name   = tb.tb_frame.f_code.co_filename if tb else "Unknown"
            line_number = tb.tb_lineno if tb else "Unknown"
            error_msg   = str(error_detail)
        else:
            file_name, line_number, error_msg = "Unknown", "Unknown", "No underlying exception"

        return (
            f"{message} | "
            f"Error: {error_msg} | "
            f"File: {file_name} | "
            f"Line: {line_number}"
        )

    def __str__(self) -> str:
        return self.error_message
"""

(PROJECT_ROOT / "src" / "custom_exception.py").write_text(textwrap.dedent(exception_code))
print("src/custom_exception.py written.")

# ============================================================
# CELL 7: Write config/data_ingestion_config.py
# Central place for all project constants.
# Change hyper-parameters here without touching src/.
#
# DATASET_NAME  : Kaggle dataset slug (owner/dataset-name)
# TARGET_DIR    : root folder where raw data lands (DVC tracks this)
# NUM_SAMPLES   : cap on how many images are used
# NUM_CLASSES   : background + gun = 2
# ============================================================

config_code = """
# --- Dataset ---
DATASET_NAME = "issaisasank/guns-object-detection"
TARGET_DIR   = "artifacts"   # DVC tracks artifacts/raw/ and artifacts/models/

# --- Subset size (set None to use the entire dataset) ---
# 300 samples keeps Colab free-tier training feasible (~10-20 min on T4)
NUM_SAMPLES  = 300

# --- Model hyper-parameters ---
NUM_CLASSES   = 2       # 1 foreground class (gun) + 1 background
LEARNING_RATE = 1e-4
EPOCHS        = 5
BATCH_SIZE    = 3       # small batch avoids OOM on T4 (16 GB VRAM)

# --- Paths ---
RAW_DATA_PATH  = f"{TARGET_DIR}/raw"
MODEL_SAVE_DIR = f"{TARGET_DIR}/models"
MODEL_FILENAME = "fasterrcnn.pth"
"""

(PROJECT_ROOT / "config" / "data_ingestion_config.py").write_text(config_code.strip())
print("config/data_ingestion_config.py written.")

# ============================================================
# CELL 8: Write src/data_ingestion.py
# Downloads the Kaggle dataset via kagglehub (uses
# KAGGLE_USERNAME + KAGGLE_KEY env vars set in Cell 2).
# Flattens nested folder structure into:
#   artifacts/raw/Images/  <- all image files
#   artifacts/raw/Labels/  <- all .txt annotation files
# The class is idempotent: re-running clears and refills.
# ============================================================

import textwrap

data_ingestion_code = """    import os
    import shutil
    import zipfile

    import kagglehub

    from src.logger import get_logger
    from src.custom_exception import CustomException
    from config.data_ingestion_config import DATASET_NAME, TARGET_DIR

    logger = get_logger(__name__)


    class DataIngestion:
        '''
        Handles end-to-end data acquisition:
          1. Download dataset from Kaggle using kagglehub
          2. Walk the downloaded folder recursively
          3. Copy images  -> artifacts/raw/Images/
             Copy labels  -> artifacts/raw/Labels/
        '''

        def __init__(self, dataset_name: str = DATASET_NAME, target_dir: str = TARGET_DIR):
            self.dataset_name = dataset_name
            self.target_dir   = target_dir
            logger.info(f"DataIngestion init | dataset={dataset_name} | target={target_dir}")

        def _create_raw_dir(self) -> str:
            '''Create artifacts/raw/ and return its path.'''
            raw_dir = os.path.join(self.target_dir, "raw")
            os.makedirs(raw_dir, exist_ok=True)
            return raw_dir

        def _flatten_dataset(self, dataset_path: str, raw_dir: str) -> None:
            '''
            Recursively walk dataset_path, then copy:
              - image files (.jpg / .jpeg / .png) -> raw_dir/Images/
              - label files (.txt)                -> raw_dir/Labels/
            Target sub-dirs are wiped first (idempotent).
            '''
            images_dst = os.path.join(raw_dir, "Images")
            labels_dst = os.path.join(raw_dir, "Labels")

            for dst in (images_dst, labels_dst):
                if os.path.exists(dst):
                    shutil.rmtree(dst)
                os.makedirs(dst)

            IMAGE_EXTS = (".jpg", ".jpeg", ".png")
            img_count = lbl_count = 0

            for root, _, files in os.walk(dataset_path):
                for fname in files:
                    src = os.path.join(root, fname)
                    if fname.lower().endswith(IMAGE_EXTS):
                        shutil.copy(src, os.path.join(images_dst, fname))
                        img_count += 1
                    elif fname.lower().endswith(".txt"):
                        shutil.copy(src, os.path.join(labels_dst, fname))
                        lbl_count += 1

            logger.info(f"Flattened: {img_count} images, {lbl_count} labels")
            if img_count == 0 or lbl_count == 0:
                raise FileNotFoundError(
                    "No images or labels found. "
                    "Check Kaggle credentials and dataset slug."
                )

        def _handle_zip(self, dataset_path: str) -> str:
            '''If kagglehub returned a .zip path, extract it first.'''
            if dataset_path.endswith(".zip"):
                extract_dir = dataset_path.replace(".zip", "")
                if not os.path.exists(extract_dir):
                    logger.info(f"Extracting zip -> {extract_dir}")
                    with zipfile.ZipFile(dataset_path, "r") as zf:
                        zf.extractall(extract_dir)
                return extract_dir
            return dataset_path

        def run(self) -> str:
            '''
            Execute full ingestion pipeline.
            Returns the path to the populated raw directory.
            '''
            try:
                raw_dir = self._create_raw_dir()
                logger.info("Downloading dataset from Kaggle ...")
                dataset_path = kagglehub.dataset_download(self.dataset_name)
                logger.info(f"Kaggle cache path: {dataset_path}")
                dataset_path = self._handle_zip(dataset_path)
                self._flatten_dataset(dataset_path, raw_dir)
                logger.info(f"Data ingestion complete. Raw data at: {raw_dir}")
                return raw_dir
            except Exception as e:
                logger.error(f"Data ingestion failed: {e}")
                raise CustomException("Data ingestion pipeline failed", e)


    if __name__ == "__main__":
        DataIngestion().run()
"""

(PROJECT_ROOT / "src" / "data_ingestion.py").write_text(textwrap.dedent(data_ingestion_code))
print("src/data_ingestion.py written.")

# ============================================================
# CELL 9: Write src/data_processing.py
# PyTorch Dataset class for the YOLO-style annotation format.
#
# Label file format (per image):
#   line 0  : <count>              <- number of bounding boxes
#   lines 1+: <x_min> <y_min> <x_max> <y_max>  (pixel coords, xyxy)
#
# Returns:
#   image  : float32 tensor [3, H, W], values in [0, 1]
#   target : dict with boxes, labels, area, image_id (on device)
# ============================================================

data_processing_code = """
import os

import cv2
import numpy as np
import torch
from torch.utils.data import Dataset

from src.logger import get_logger
from src.custom_exception import CustomException

logger = get_logger(__name__)


class GunDataset(Dataset):
    '''
    Custom PyTorch Dataset for gun object detection.

    Directory layout expected:
        root/
          Images/   <- .jpg / .jpeg / .png files
          Labels/   <- matching .txt files (xyxy pixel-coord format)

    Returns image tensor [3,H,W] and target dict compatible
    with torchvision Faster R-CNN.
    '''

    def __init__(self, root: str, device: str = "cpu"):
        self.image_dir  = os.path.join(root, "Images")
        self.labels_dir = os.path.join(root, "Labels")
        self.device     = device

        # Sorted lists guarantee image[i] matches label[i]
        self.img_names = sorted(os.listdir(self.image_dir))

        logger.info(
            f"GunDataset ready | {len(self.img_names)} images | device={device}"
        )

    def __len__(self) -> int:
        return len(self.img_names)

    def __getitem__(self, idx: int):
        try:
            # --- Load & normalise image ---
            img_path = os.path.join(self.image_dir, self.img_names[idx])
            bgr = cv2.imread(img_path)
            if bgr is None:
                raise FileNotFoundError(f"cv2.imread returned None for {img_path}")

            rgb   = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB).astype(np.float32)
            img_t = torch.as_tensor(rgb / 255.0).permute(2, 0, 1)  # [3,H,W]

            # --- Load bounding-box annotations ---
            stem       = os.path.splitext(self.img_names[idx])[0]
            label_path = os.path.join(self.labels_dir, stem + ".txt")

            # Default empty target (handles images with no annotations)
            target = {
                "boxes"   : torch.zeros((0, 4), dtype=torch.float32),
                "labels"  : torch.zeros(0,       dtype=torch.int64),
                "area"    : torch.zeros(0,       dtype=torch.float32),
                "image_id": torch.tensor([idx]),
            }

            if os.path.exists(label_path):
                with open(label_path, "r") as f:
                    lines     = f.read().strip().splitlines()
                    box_count = int(lines[0]) if lines else 0
                    boxes     = [
                        list(map(int, lines[i + 1].split()))
                        for i in range(box_count)
                        if i + 1 < len(lines)
                    ]

                if boxes:
                    areas = [(b[2] - b[0]) * (b[3] - b[1]) for b in boxes]
                    target["boxes"]  = torch.tensor(boxes,  dtype=torch.float32)
                    target["labels"] = torch.ones(len(boxes), dtype=torch.int64)
                    target["area"]   = torch.tensor(areas,  dtype=torch.float32)

            # Move tensors to the target device
            img_t  = img_t.to(self.device)
            target = {k: v.to(self.device) for k, v in target.items()}

            return img_t, target

        except Exception as e:
            logger.error(f"Error loading index {idx}: {e}")
            raise CustomException(f"Failed to load sample at index {idx}", e)
"""

(PROJECT_ROOT / "src" / "data_processing.py").write_text(data_processing_code.strip())
print("src/data_processing.py written.")

# ============================================================
# CELL 10: Write src/model_architecture.py
# Builds Faster R-CNN ResNet-50 FPN pre-trained on COCO,
# then replaces the classification head for our 2-class task
# (background + gun).
# Uses the modern `weights=` API (no deprecation warning).
# ============================================================

model_arch_code = """
import torch
from torchvision.models.detection import (
    fasterrcnn_resnet50_fpn,
    FasterRCNN_ResNet50_FPN_Weights,
)
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor

from src.logger import get_logger
from src.custom_exception import CustomException

logger = get_logger(__name__)


class FasterRCNNModel:
    '''
    Wraps torchvision's Faster R-CNN ResNet-50 FPN and adapts its
    prediction head for a custom number of classes.

    Usage:
        wrapper = FasterRCNNModel(num_classes=2, device="cuda")
        model   = wrapper.model   # the raw nn.Module ready for training
    '''

    def __init__(self, num_classes: int, device: str):
        self.num_classes = num_classes
        self.device      = device
        self.model       = self._build().to(device)
        logger.info(
            f"FasterRCNNModel ready | num_classes={num_classes} | device={device}"
        )

    def _build(self):
        '''
        Load COCO-pretrained weights, then swap the RoI box predictor
        head so output dimensionality matches num_classes.
        '''
        try:
            weights = FasterRCNN_ResNet50_FPN_Weights.DEFAULT
            model   = fasterrcnn_resnet50_fpn(weights=weights)

            # Only the final head is replaced; backbone stays frozen initially
            in_features = model.roi_heads.box_predictor.cls_score.in_features
            model.roi_heads.box_predictor = FastRCNNPredictor(
                in_features, self.num_classes
            )

            logger.info("Faster R-CNN head replaced for custom classes.")
            return model

        except Exception as e:
            logger.error(f"Model build failed: {e}")
            raise CustomException("Failed to build Faster R-CNN model", e)
"""

(PROJECT_ROOT / "src" / "model_architecture.py").write_text(model_arch_code.strip())
print("src/model_architecture.py written.")

# ============================================================
# CELL 11: Write src/model_training.py
# Orchestrates: dataset split -> DataLoader -> train loop ->
# validation -> checkpoint saving.
#
# Integrations:
#   TensorBoard : Loss/train_batch, Loss/train_epoch, Loss/val_epoch
#   MLflow      : hyper-params, per-epoch metrics, final model artifact
#   Checkpoints : state dict saved after every epoch
#
# NOTE: Faster R-CNN returns a loss dict only in train() mode.
# For validation loss we keep model.train() + torch.no_grad().
# ============================================================

model_training_code = """
import os
import time

import mlflow
import mlflow.pytorch
import torch
from torch import optim
from torch.utils.data import DataLoader, random_split
from torch.utils.tensorboard import SummaryWriter

from config.data_ingestion_config import (
    NUM_CLASSES, LEARNING_RATE, EPOCHS, BATCH_SIZE,
    RAW_DATA_PATH, MODEL_SAVE_DIR, MODEL_FILENAME, NUM_SAMPLES,
)
from src.custom_exception import CustomException
from src.data_processing import GunDataset
from src.logger import get_logger
from src.model_architecture import FasterRCNNModel

logger = get_logger(__name__)


class ModelTraining:
    '''
    Full training pipeline for Faster R-CNN on the guns dataset.

    Hyper-parameters are read from config/data_ingestion_config.py
    but can be overridden at instantiation for quick experiments.
    '''

    def __init__(
        self,
        num_classes   : int   = NUM_CLASSES,
        learning_rate : float = LEARNING_RATE,
        epochs        : int   = EPOCHS,
        batch_size    : int   = BATCH_SIZE,
        dataset_path  : str   = RAW_DATA_PATH,
        model_save_dir: str   = MODEL_SAVE_DIR,
        num_samples   : int   = NUM_SAMPLES,
    ):
        self.num_classes    = num_classes
        self.learning_rate  = learning_rate
        self.epochs         = epochs
        self.batch_size     = batch_size
        self.dataset_path   = dataset_path
        self.model_save_dir = model_save_dir
        self.num_samples    = num_samples

        # Device selection (Colab T4 GPU recommended)
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        logger.info(f"Training device: {self.device}")

        os.makedirs(self.model_save_dir, exist_ok=True)

        # TensorBoard writer (unique dir per run)
        ts = time.strftime("%Y%m%d-%H%M%S")
        self.log_dir = f"tensorboard_logs/{ts}"
        os.makedirs(self.log_dir, exist_ok=True)
        self.writer  = SummaryWriter(log_dir=self.log_dir)
        logger.info(f"TensorBoard logs -> {self.log_dir}")

        # Build model and optimizer
        try:
            self.model     = FasterRCNNModel(self.num_classes, self.device).model
            self.optimizer = optim.Adam(
                self.model.parameters(), lr=self.learning_rate
            )
            logger.info("Model and optimizer initialised.")
        except Exception as e:
            raise CustomException("Failed to initialise model training", e)

    @staticmethod
    def collate_fn(batch):
        '''Custom collate needed because each sample has variable-size boxes.'''
        return tuple(zip(*batch))

    def _build_loaders(self):
        '''Create train/val DataLoaders with 80/20 split.'''
        try:
            full_dataset = GunDataset(self.dataset_path, self.device)

            # Cap to NUM_SAMPLES so training stays feasible on free Colab
            if self.num_samples and self.num_samples < len(full_dataset):
                full_dataset = torch.utils.data.Subset(
                    full_dataset, range(self.num_samples)
                )
                logger.info(f"Dataset capped to {self.num_samples} samples.")

            train_size = int(0.8 * len(full_dataset))
            val_size   = len(full_dataset) - train_size
            train_ds, val_ds = random_split(full_dataset, [train_size, val_size])

            loader_kw = dict(
                batch_size=self.batch_size,
                num_workers=0,          # 0 avoids CUDA fork issues in Colab
                collate_fn=self.collate_fn,
            )
            train_loader = DataLoader(train_ds, shuffle=True,  **loader_kw)
            val_loader   = DataLoader(val_ds,   shuffle=False, **loader_kw)

            logger.info(f"Loaders ready | train={len(train_ds)} | val={len(val_ds)}")
            return train_loader, val_loader

        except Exception as e:
            raise CustomException("Failed to build DataLoaders", e)

    def _sum_losses(self, loss_dict) -> torch.Tensor:
        '''Sum all loss tensors returned by Faster R-CNN.'''
        if isinstance(loss_dict, dict):
            return sum(v for v in loss_dict.values() if isinstance(v, torch.Tensor))
        return loss_dict[0]

    def run(self):
        '''
        Execute end-to-end training.
        Saves a checkpoint after every epoch and writes the final model
        to artifacts/models/fasterrcnn.pth (DVC-tracked output).
        '''
        try:
            train_loader, val_loader = self._build_loaders()

            with mlflow.start_run():
                # Log all hyper-params to MLflow / DagsHub
                mlflow.log_params({
                    "num_classes"   : self.num_classes,
                    "learning_rate" : self.learning_rate,
                    "epochs"        : self.epochs,
                    "batch_size"    : self.batch_size,
                    "num_samples"   : self.num_samples,
                    "device"        : self.device,
                    "model"         : "FasterRCNN_ResNet50_FPN",
                })

                global_step = 0

                for epoch in range(1, self.epochs + 1):
                    # ---- Training phase ----
                    self.model.train()
                    epoch_loss = 0.0

                    for batch_idx, (images, targets) in enumerate(train_loader):
                        self.optimizer.zero_grad()

                        loss_dict  = self.model(list(images), list(targets))
                        total_loss = self._sum_losses(loss_dict)

                        total_loss.backward()
                        self.optimizer.step()

                        batch_loss  = total_loss.item()
                        epoch_loss += batch_loss

                        # Per-batch TensorBoard log
                        self.writer.add_scalar(
                            "Loss/train_batch", batch_loss, global_step
                        )
                        global_step += 1

                        if batch_idx % 10 == 0:
                            logger.info(
                                f"Epoch {epoch}/{self.epochs} | "
                                f"Batch {batch_idx}/{len(train_loader)} | "
                                f"Loss: {batch_loss:.4f}"
                            )

                    avg_train = epoch_loss / len(train_loader)
                    self.writer.add_scalar("Loss/train_epoch", avg_train, epoch)
                    mlflow.log_metric("train_loss", avg_train, step=epoch)
                    logger.info(
                        f"Epoch {epoch} done | avg_train_loss={avg_train:.4f}"
                    )

                    # ---- Validation phase ----
                    # Keep model.train() + no_grad() to get a loss dict
                    self.model.train()
                    val_loss_total = 0.0
                    with torch.no_grad():
                        for images, targets in val_loader:
                            val_ld          = self.model(list(images), list(targets))
                            val_loss_total += self._sum_losses(val_ld).item()

                    avg_val = val_loss_total / len(val_loader)
                    self.writer.add_scalar("Loss/val_epoch", avg_val, epoch)
                    mlflow.log_metric("val_loss", avg_val, step=epoch)
                    logger.info(f"   val_loss={avg_val:.4f}")

                    # ---- Epoch checkpoint ----
                    ckpt = os.path.join(
                        self.model_save_dir, f"fasterrcnn_epoch{epoch}.pth"
                    )
                    torch.save(self.model.state_dict(), ckpt)
                    logger.info(f"   Checkpoint -> {ckpt}")

                # ---- Final model (DVC output) ----
                final_path = os.path.join(self.model_save_dir, MODEL_FILENAME)
                torch.save(self.model.state_dict(), final_path)
                logger.info(f"Final model saved -> {final_path}")

                # Log model and checkpoint to MLflow artifacts
                mlflow.pytorch.log_model(
                    self.model, artifact_path="faster_rcnn_model"
                )
                mlflow.log_artifact(final_path, artifact_path="checkpoints")

                self.writer.flush()
                self.writer.close()

            logger.info("Training complete.")
            return final_path

        except Exception as e:
            logger.error(f"Training failed: {e}")
            raise CustomException("Model training pipeline failed", e)


if __name__ == "__main__":
    ModelTraining().run()
"""

(PROJECT_ROOT / "src" / "model_training.py").write_text(model_training_code.strip())
print("src/model_training.py written.")

# ============================================================
# CELL 12: Write dvc.yaml (DVC pipeline definition)
# Two stages:
#   data_ingestion  -> downloads Kaggle data into artifacts/raw/
#   model_training  -> trains model, saves artifacts/models/fasterrcnn.pth
#
# `deps` = inputs DVC watches for changes (triggers re-run)
# `outs` = outputs DVC caches/tracks (skipped if up-to-date)
# ============================================================

dvc_yaml_content = """
stages:
  data_ingestion:
    cmd: >-
      python -c
      "import sys; sys.path.insert(0, '.');
      from src.data_ingestion import DataIngestion;
      DataIngestion().run()"
    deps:
      - src/data_ingestion.py
      - config/data_ingestion_config.py
    outs:
      - artifacts/raw/

  model_training:
    cmd: >-
      python -c
      "import sys; sys.path.insert(0, '.');
      from src.model_training import ModelTraining;
      ModelTraining().run()"
    deps:
      - src/model_training.py
      - src/model_architecture.py
      - src/data_processing.py
      - config/data_ingestion_config.py
      - artifacts/raw/
    outs:
      - artifacts/models/fasterrcnn.pth
"""

(PROJECT_ROOT / "dvc.yaml").write_text(dvc_yaml_content.strip())
print("dvc.yaml written.")

# ============================================================
# CELL 13: Initialise Git + DVC
# DVC requires a Git repository to store metadata (.dvc/,
# dvc.lock). We init a bare repo, configure a dummy identity,
# then run `dvc init`.
# ============================================================

import subprocess

def run_cmd(cmd, cwd=str(PROJECT_ROOT)):
    """Run a shell command and print output."""
    result = subprocess.run(
        cmd, shell=True, capture_output=True, text=True, cwd=cwd
    )
    if result.stdout.strip():
        print(result.stdout.strip())
    if result.returncode != 0 and result.stderr.strip():
        print("STDERR:", result.stderr.strip())
    return result

# Git identity required for commits (Colab has none by default)
run_cmd('git config --global user.email "colab@example.com"')
run_cmd('git config --global user.name  "Colab Runner"')

# Initialise git repo
if not (PROJECT_ROOT / ".git").exists():
    run_cmd("git init")
    print("git init done.")
else:
    print("Git already initialised.")

# Initialise DVC
if not (PROJECT_ROOT / ".dvc").exists():
    run_cmd("dvc init")
    print("dvc init done.")
else:
    print("DVC already initialised.")

# Stage all files for initial commit
run_cmd("git add .")
r = run_cmd('git commit -m "feat: initial project scaffold with DVC"')
if r.returncode == 0:
    print("Initial git commit created.")
else:
    print("Nothing new to commit (already committed).")

# ============================================================
# CELL 14: Run DVC pipeline with `dvc repro`
# dvc repro reads dvc.yaml, checks which stages are stale
# (deps changed or outs missing) and re-executes only those.
#
# Stage 1 - data_ingestion : downloads & flattens dataset (~2-5 min)
# Stage 2 - model_training : trains Faster R-CNN (~10-20 min on T4)
#
# Progress is printed to stdout AND written to logs/.
# ============================================================

import subprocess

print("Starting DVC pipeline (dvc repro) ...\n")

result = subprocess.run(
    "dvc repro --verbose",
    shell=True,
    cwd=str(PROJECT_ROOT),
    text=True,
)

if result.returncode == 0:
    print("\nDVC pipeline completed successfully!")
else:
    print("\nDVC pipeline failed. Check logs/ for details.")
    raise RuntimeError("dvc repro failed")

# ============================================================
# CELL 15: Verify artifacts produced by DVC
# Checks that images, labels, and the trained model exist.
# Also prints the tail of the latest log file.
# ============================================================

import os, pathlib

raw_images = list((PROJECT_ROOT / "artifacts/raw/Images").glob("*"))
raw_labels = list((PROJECT_ROOT / "artifacts/raw/Labels").glob("*"))
model_file  = PROJECT_ROOT / "artifacts/models/fasterrcnn.pth"

print(f"Raw images : {len(raw_images)}")
print(f"Raw labels : {len(raw_labels)}")
print(f"Model file exists: {model_file.exists()} | path: {model_file}")

# Show tail of latest log
logs = sorted((PROJECT_ROOT / "logs").glob("*.log"))
if logs:
    print(f"\nLatest log: {logs[-1].name}")
    lines = logs[-1].read_text().splitlines()
    for l in lines[-30:]:
        print(l)

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# CELL 16: Launch TensorBoard
# Displays Loss/train_batch, Loss/train_epoch, Loss/val_epoch.
# A public URL will appear - click it to open the dashboard.
# ============================================================

# %load_ext tensorboard
# %tensorboard --logdir {PROJECT_ROOT}/tensorboard_logs

# ============================================================
# CELL 17: Quick inference smoke-test
# Loads the saved checkpoint, runs it on the first image,
# and draws predicted boxes (score > 0.5) with matplotlib.
# ============================================================

import sys
sys.path.insert(0, str(PROJECT_ROOT))

import torch
import cv2
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches

from src.model_architecture import FasterRCNNModel

DEVICE     = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_PATH = PROJECT_ROOT / "artifacts/models/fasterrcnn.pth"
IMG_DIR    = PROJECT_ROOT / "artifacts/raw/Images"
SCORE_THR  = 0.5   # confidence threshold for displaying boxes

# --- Load model ---
wrapper = FasterRCNNModel(num_classes=2, device=DEVICE)
wrapper.model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
wrapper.model.eval()
print(f"Model loaded from {MODEL_PATH}")

# --- Pick test image ---
test_img_path = sorted(IMG_DIR.iterdir())[0]
bgr  = cv2.imread(str(test_img_path))
rgb  = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
img_t = torch.as_tensor(rgb).permute(2, 0, 1).unsqueeze(0).to(DEVICE)

# --- Inference ---
with torch.no_grad():
    preds = wrapper.model(img_t)

boxes  = preds[0]["boxes"].cpu().numpy()
scores = preds[0]["scores"].cpu().numpy()
print(f"Total detections: {len(boxes)} | Above threshold: {(scores > SCORE_THR).sum()}")

# --- Visualise ---
fig, ax = plt.subplots(1, 1, figsize=(10, 8))
ax.imshow(rgb)
ax.set_title(f"Inference: {test_img_path.name}", fontsize=13)

for box, score in zip(boxes, scores):
    if score > SCORE_THR:
        x1, y1, x2, y2 = box
        rect = patches.Rectangle(
            (x1, y1), x2 - x1, y2 - y1,
            linewidth=2, edgecolor="red", facecolor="none"
        )
        ax.add_patch(rect)
        ax.text(x1, y1 - 5, f"{score:.2f}", color="red", fontsize=9)

ax.axis("off")
plt.tight_layout()
plt.savefig(str(PROJECT_ROOT / "artifacts/inference_sample.png"), dpi=150, bbox_inches="tight")
plt.show()
print("Inference image saved to artifacts/inference_sample.png")

# ============================================================
# CELL 18: Commit DVC lock + logs to Git
# After dvc repro, DVC creates/updates dvc.lock which records
# hashes of all stage inputs/outputs.
# Committing this lets Git track exactly which data was used.
# Large files (images, .pth) stay in DVC cache, NOT in Git.
#
# You can later push to GitHub:
#   git remote add origin https://github.com/Prithu-Sarkar/GEN-AI-INDUSTRY-PROJECT_2.git
#   git push -u origin main
# ============================================================

import subprocess

def git(cmd):
    r = subprocess.run(cmd, shell=True, cwd=str(PROJECT_ROOT),
                       capture_output=True, text=True)
    if r.stdout.strip():
        print(r.stdout.strip())
    return r

git("git add dvc.lock dvc.yaml .dvc/ logs/ tensorboard_logs/")
git("git add artifacts/models/  --force")  # add model checkpoint path
r = git('git commit -m "chore: DVC repro complete - lock + logs" --allow-empty')

if r.returncode == 0:
    print("Git commit done.")

print()
print("To push to GitHub later:")
print("  git remote add origin https://github.com/Prithu-Sarkar/GEN-AI-INDUSTRY-PROJECT_2.git")
print("  git branch -M main")
print("  git push -u origin main")

# ============================================================
# CELL 19: Print MLflow run summary
# Shows parameters and metrics logged during training.
# If USE_DAGSHUB=True, these are also visible on DagsHub.
# ============================================================

import mlflow, os

uri = os.environ.get("MLFLOW_TRACKING_URI", "not set")
print(f"MLflow tracking URI: {uri}\n")

client = mlflow.MlflowClient()

for exp in client.search_experiments():
    runs = client.search_runs(
        exp.experiment_id,
        order_by=["start_time DESC"],
        max_results=5
    )
    for run in runs:
        print(f"Run ID : {run.info.run_id}")
        print(f"Status : {run.info.status}")
        print("Params :", run.data.params)
        print("Metrics:", {k: round(v, 4) for k, v in run.data.metrics.items()})
        print("-" * 60)

# Zip the entire /content/guns_detection folder
!zip -r /content/guns_detection.zip /content/guns_detection

# Download the zip file to your local machine
from google.colab import files
files.download('/content/guns_detection.zip')