# -*- coding: utf-8 -*-
"""student_engagement_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13X4X2d3Ggn5zbCF7OA6HeaUeqQBKpQax

# 🎓 Student Learning Engagement Analyzer
## End-to-End ML Pipeline — Google Colab Notebook

This notebook covers the **complete project pipeline**:
1. Environment setup & secret injection
2. Install dependencies
3. Upload project zip → unpack
4. Data loading & understanding (N1)
5. Engagement & target design (N2)
6. Temporal engagement analysis (N3)
7. Model training + **MLflow / DagsHub** tracking (N4)
8. Evaluation & explainability
9. Recommendation engine
10. End-to-end prediction pipeline
11. Batch predictions on test set
12. Save all outputs & **download as ZIP**

## 🔐 Step 1 — Set Environment Variables (Colab Secrets)
"""

import os
from google.colab import userdata

# ── MongoDB (from Colab Secrets) ──────────────────────────────────────────────
os.environ['MONGO_DB_URL'] = userdata.get('MONGO_DB_URL')

# ── MLflow / DagsHub ──────────────────────────────────────────────────────────
USE_DAGSHUB = True  # ✅ Set to False to use local MLflow

if USE_DAGSHUB:
    os.environ['MLFLOW_TRACKING_URI']      = userdata.get('MLFLOW_TRACKING_URI')
    os.environ['MLFLOW_TRACKING_USERNAME'] = userdata.get('MLFLOW_TRACKING_USERNAME')
    os.environ['MLFLOW_TRACKING_PASSWORD'] = userdata.get('MLFLOW_TRACKING_PASSWORD')
else:
    # Local MLflow — logs saved inside Colab
    os.environ['MLFLOW_TRACKING_URI'] = f"file://{os.getcwd()}/mlruns"

print('✅ Env vars set.')
print(f"   MLFLOW_TRACKING_URI = {os.environ['MLFLOW_TRACKING_URI']}")

"""## 📦 Step 2 — Install Dependencies"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install pandas numpy scikit-learn joblib pyyaml mlflow dagshub pymongo

"""## 📁 Step 3 — Upload & Unpack Project Code

Upload **`project_code.zip`** when the file picker appears below.
"""

from google.colab import files
import zipfile, os

print("📂 Please upload project_code.zip ...")
uploaded = files.upload()

zip_name = list(uploaded.keys())[0]
print(f"\n✅ Uploaded: {zip_name}")

os.makedirs("/content/project", exist_ok=True)
with zipfile.ZipFile(zip_name, "r") as zf:
    zf.extractall("/content/project")
print("✅ Extracted to /content/project")

for item in sorted(os.listdir("/content/project")):
    print("   ", item)

"""## 🗂️ Step 4 — Configure Paths & Python Path"""

import sys
from pathlib import Path

PROJECT_ROOT = Path("/content/project")
DATASET_PATH = PROJECT_ROOT / "dataset" / "artefacts"
MODEL_PATH   = PROJECT_ROOT / "models"  / "artefacts"
CONFIG_PATH  = PROJECT_ROOT / "config"
OUTPUT_DIR   = Path("/content/outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT :", PROJECT_ROOT)
print("DATASET_PATH :", DATASET_PATH)
print("MODEL_PATH   :", MODEL_PATH)
print("CONFIG_PATH  :", CONFIG_PATH)
print("OUTPUT_DIR   :", OUTPUT_DIR)

for p in [DATASET_PATH, MODEL_PATH, CONFIG_PATH]:
    found = list(p.iterdir()) if p.exists() else []
    print(f"\n{p.name}/ ({len(found)} files):")
    for f in found:
        print("    ", f.name)

"""## 📊 Step 5 — Data Understanding & Memory-Safe Loading (N1)"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

df_v1 = pd.read_csv(DATASET_PATH / "student_master_v1.csv")
df_v2 = pd.read_csv(DATASET_PATH / "student_master_v2.csv")
df_v3 = pd.read_csv(DATASET_PATH / "student_master_v3_temporal.csv")

print(f"v1 shape : {df_v1.shape}")
print(f"v2 shape : {df_v2.shape}")
print(f"v3 shape : {df_v3.shape}")

print("=== Dataset V1 — First 5 rows ===")
display(df_v1.head())

print("\n=== Data Types ===")
display(df_v1.dtypes.to_frame("dtype"))

print("\n=== Nulls per column ===")
display(df_v1.isnull().sum().to_frame("null_count"))

print("=== V1 Descriptive Statistics ===")
display(df_v1.describe().T)

new_cols = set(df_v2.columns) - set(df_v1.columns)
print(f"New columns in v2 vs v1: {new_cols}")
display(df_v2.head(3))

print("=== Dataset V3 (Temporal) — Info ===")
df_v3.info()
print("\n=== First 5 rows ===")
display(df_v3.head())

"""## 🎯 Step 6 — Engagement Understanding & Target Design (N2)"""

df = df_v2.copy()
print("total_click stats:")
print(df["total_click"].describe())

df["click_bin"] = pd.qcut(df["total_click"], q=5, labels=False, duplicates="drop")
click_success = (
    df.groupby("click_bin")["final_result"]
    .apply(lambda x: (x == "Pass").mean())
    .reset_index()
)
click_success.columns = ["click_bin", "pass_rate"]
print("Pass rate by click quintile:")
display(click_success)

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].bar(click_success["click_bin"], click_success["pass_rate"], color="steelblue")
axes[0].set_xlabel("Click Quintile (0=low, 4=high)")
axes[0].set_ylabel("Pass Rate")
axes[0].set_title("Pass Rate by Click Quintile")

outcome_counts = df["final_result"].value_counts()
axes[1].pie(outcome_counts, labels=outcome_counts.index, autopct="%1.1f%%", startangle=140)
axes[1].set_title("Final Result Distribution")

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "01_engagement_overview.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Saved: 01_engagement_overview.png")

df["at_risk"] = df["final_result"].isin(["Withdrawn", "Fail"]).astype(int)

print("Target distribution:")
print(df["at_risk"].value_counts())
print(f"At-risk rate: {df['at_risk'].mean():.2%}")

"""## ⏱️ Step 7 — Temporal Engagement & Early Signals (N3)"""

df_t = df_v3.copy()
print("Temporal dataset columns:")
print(df_t.columns.tolist())
print(f"\nShape: {df_t.shape}")

feature_cols = [
    "total_click",
    "early_click",
    "early_active_days",
    "first_activity_day",
    "pre_course_engaged",
]

available = [c for c in feature_cols if c in df_t.columns]

if "at_risk" not in df_t.columns and "final_result" in df_t.columns:
    df_t["at_risk"] = df_t["final_result"].isin(["Withdrawn", "Fail"]).astype(int)

corr = df_t[available + ["at_risk"]].corr()["at_risk"].sort_values()
print("Correlation with at_risk target:")
display(corr.to_frame("correlation"))

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

for ax, col in zip(axes, ["total_click", "early_click", "early_active_days"]):
    if col not in df_t.columns:
        continue
    for risk, grp in df_t.groupby("at_risk"):
        ax.hist(
            grp[col].dropna().clip(upper=grp[col].quantile(0.95)),
            bins=40, alpha=0.6, label=f"at_risk={risk}", density=True
        )
    ax.set_title(col)
    ax.legend()

plt.suptitle("Feature Distributions by Risk Group", fontsize=14)
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "02_temporal_signals.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Saved: 02_temporal_signals.png")

"""## 🤖 Step 8 — Model Training with MLflow / DagsHub Tracking (N4)"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report, confusion_matrix,
    roc_auc_score, accuracy_score, roc_curve
)
import joblib

feature_cols = [
    "total_click",
    "early_click",
    "early_active_days",
    "first_activity_day",
    "pre_course_engaged",
]

if "at_risk" not in df_t.columns:
    df_t["at_risk"] = df_t["final_result"].isin(["Withdrawn", "Fail"]).astype(int)

X = df_t[feature_cols].copy()
y = df_t["at_risk"].copy()

# Handle students who never started (NaN first_activity_day → 999)
X["first_activity_day"] = X["first_activity_day"].fillna(999)
X = X.fillna(0)

print(f"X shape : {X.shape}")
print(f"y distribution:\n{y.value_counts()}")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
print(f"Train: {X_train.shape}  |  Test: {X_test.shape}")

import mlflow
import mlflow.sklearn

mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])

if USE_DAGSHUB:
    import dagshub
    tracking_uri = os.environ["MLFLOW_TRACKING_URI"]
    # Parse owner/repo from DagsHub URI: https://dagshub.com/<owner>/<repo>.mlflow
    parts = tracking_uri.replace("https://dagshub.com/", "").replace(".mlflow", "").split("/")
    repo_owner, repo_name = parts[0], parts[1]
    dagshub.init(repo_owner=repo_owner, repo_name=repo_name, mlflow=True)

mlflow.set_experiment("student-engagement-risk")
print(f"MLflow tracking URI : {mlflow.get_tracking_uri()}")

MAX_DEPTH   = 5
MIN_SAMPLES = 20

with mlflow.start_run(run_name="DecisionTree_v1") as run:

    mlflow.log_param("max_depth",        MAX_DEPTH)
    mlflow.log_param("min_samples_leaf", MIN_SAMPLES)
    mlflow.log_param("train_size",       len(X_train))
    mlflow.log_param("test_size",        len(X_test))

    model = DecisionTreeClassifier(
        max_depth=MAX_DEPTH,
        min_samples_leaf=MIN_SAMPLES,
        random_state=42
    )
    model.fit(X_train, y_train)

    y_pred  = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    acc     = accuracy_score(y_test, y_pred)
    roc_auc = roc_auc_score(y_test, y_proba)

    mlflow.log_metric("accuracy", acc)
    mlflow.log_metric("roc_auc",  roc_auc)
    mlflow.sklearn.log_model(model, artifact_path="model")

    RUN_ID = run.info.run_id
    print(f"✅ Run ID  : {RUN_ID}")
    print(f"   Accuracy: {acc:.4f}")
    print(f"   ROC-AUC : {roc_auc:.4f}")

"""## 📈 Step 9 — Model Evaluation & Explainability"""

print("=== Classification Report ===")
print(classification_report(y_test, y_pred, target_names=["Not At Risk", "At Risk"]))

cm = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cm)

importance = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Feature importance
importance.plot(kind="bar", ax=axes[0], color="coral", edgecolor="black")
axes[0].set_title("Feature Importances (Decision Tree)")
axes[0].set_ylabel("Importance")
axes[0].tick_params(axis="x", rotation=45)

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
axes[1].plot(fpr, tpr, color="steelblue", lw=2, label=f"AUC = {roc_auc:.3f}")
axes[1].plot([0, 1], [0, 1], "k--", lw=1)
axes[1].set_xlabel("False Positive Rate")
axes[1].set_ylabel("True Positive Rate")
axes[1].set_title("ROC Curve")
axes[1].legend()

plt.tight_layout()
plt.savefig(OUTPUT_DIR / "03_model_evaluation.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Saved: 03_model_evaluation.png")

def explain_tree_decision(model, input_df, feature_names):
    node_indicators = model.decision_path(input_df)
    feature   = model.tree_.feature
    threshold = model.tree_.threshold
    explanation = []
    for node_id in node_indicators.indices:
        if feature[node_id] != -2:  # -2 == leaf node
            fname  = feature_names[feature[node_id]]
            thresh = threshold[node_id]
            val    = input_df.iloc[0][fname]
            direction = "<=" if val <= thresh else ">"
            explanation.append(
                f"{fname.replace('_', ' ').title()} {direction} {int(thresh)}"
            )
    return explanation

# Demonstrate on first test sample
sample_df = X_test.iloc[[0]]
explanation = explain_tree_decision(model, sample_df, feature_cols)

print("Decision path for sample student:")
for step in explanation:
    print(f"  → {step}")
print(f"  Prediction: at_risk={model.predict(sample_df)[0]}  (prob={model.predict_proba(sample_df)[0][1]:.3f})")

"""## 💡 Step 10 — Recommendation Engine"""

import yaml

with open(CONFIG_PATH / "config.yaml") as f:
    THRESHOLDS = yaml.safe_load(f)

print("Loaded config:")
print(THRESHOLDS)

def generate_recommendations(risk_probability, student_input):
    observations = []
    actions      = []

    if student_input["early_active_days"] == 0:
        observations.append("No engagement in early course period")
        actions.append("Start with introductory materials immediately.")

    if student_input["early_click"] < THRESHOLDS["early_engagement"]["min_early_click"]:
        observations.append("Low early interaction with course content")
        actions.append("Watch intro videos and explore course structure")

    if student_input["first_activity_day"] > 0:
        observations.append("Late course start compared to peers")
        actions.append("Follow a structured 7-day recovery plan")

    if risk_probability >= THRESHOLDS["risk_levels"]["high"]:
        actions.append("Schedule academic support or mentoring session.")

    return observations, actions

"""## 🔄 Step 11 — End-to-End Prediction Pipeline"""

def predict_and_recommend(student_dict, model, feature_cols):
    required = ["total_click", "early_click", "early_active_days",
                "first_activity_day", "pre_course_engaged"]
    missing = [k for k in required if k not in student_dict]
    if missing:
        raise ValueError(f"Missing required fields: {missing}")

    input_df = pd.DataFrame([student_dict])
    input_df["first_activity_day"] = input_df["first_activity_day"].fillna(999)
    input_df = input_df[feature_cols].fillna(0)

    risk_probability = model.predict_proba(input_df)[0][1]

    if risk_probability >= THRESHOLDS["risk_levels"]["high"]:
        risk_level = "High"
    elif risk_probability >= THRESHOLDS["risk_levels"]["medium"]:
        risk_level = "Medium"
    else:
        risk_level = "Low"

    observations, actions = generate_recommendations(risk_probability, student_dict)
    tree_explanation      = explain_tree_decision(model, input_df, feature_cols)

    return {
        "risk_probability" : round(float(risk_probability), 3),
        "risk_level"       : risk_level,
        "observations"     : observations,
        "recommendations"  : actions,
        "model_explanation": tree_explanation,
    }

# ── High-risk student example ─────────────────────────────────────────────────
sample_high_risk = {
    "total_click"       : 80,
    "early_click"       : 0,
    "early_active_days" : 0,
    "first_activity_day": 15,
    "pre_course_engaged": 0,
}

result = predict_and_recommend(sample_high_risk, model, feature_cols)

print("=" * 55)
print(f"  Risk Level      : {result['risk_level']}")
print(f"  Risk Probability: {result['risk_probability']}")
print("\n  Observations:")
for obs in result["observations"]:
    print(f"    ⚠️  {obs}")
print("\n  Recommendations:")
for act in result["recommendations"]:
    print(f"    ✅  {act}")
print("\n  Model Decision Path:")
for step in result["model_explanation"]:
    print(f"    →  {step}")

# ── Low-risk student example ──────────────────────────────────────────────────
sample_low_risk = {
    "total_click"       : 800,
    "early_click"       : 120,
    "early_active_days" : 8,
    "first_activity_day": -5,
    "pre_course_engaged": 1,
}

result2 = predict_and_recommend(sample_low_risk, model, feature_cols)
print(f"Risk Level      : {result2['risk_level']}")
print(f"Risk Probability: {result2['risk_probability']}")

"""## 💾 Step 12 — Save Trained Model & Output Files"""

# Save retrained model
model_out_path = OUTPUT_DIR / "finalized_model.joblib"
joblib.dump(model, model_out_path)
print(f"✅ Model saved       : {model_out_path}")

# Save metrics
metrics_df = pd.DataFrame({"metric": ["accuracy", "roc_auc"], "value": [acc, roc_auc]})
metrics_df.to_csv(OUTPUT_DIR / "model_metrics.csv", index=False)
print("✅ Metrics saved     : model_metrics.csv")

# Save feature importances
importance.to_csv(OUTPUT_DIR / "feature_importance.csv", header=["importance"])
print("✅ Importances saved : feature_importance.csv")

print("\nAll output files so far:")
for f in sorted(OUTPUT_DIR.iterdir()):
    print(f"   {f.name}")

"""## 📋 Step 13 — Batch Predictions on Test Set"""

test_results = X_test.copy()
test_results["true_at_risk"]      = y_test.values
test_results["predicted_at_risk"] = y_pred
test_results["risk_probability"]  = y_proba

def map_risk_level(prob):
    if prob >= THRESHOLDS["risk_levels"]["high"]:
        return "High"
    elif prob >= THRESHOLDS["risk_levels"]["medium"]:
        return "Medium"
    return "Low"

test_results["risk_level"] = test_results["risk_probability"].apply(map_risk_level)
test_results.to_csv(OUTPUT_DIR / "test_predictions.csv", index=False)

print(f"✅ Test predictions saved ({len(test_results)} rows)")
display(test_results.head(10))

risk_summary = test_results["risk_level"].value_counts()
print("Predicted Risk Level Distribution:")
display(risk_summary.to_frame("count"))

fig, ax = plt.subplots(figsize=(6, 4))
colors = {"High": "#d9534f", "Medium": "#f0ad4e", "Low": "#5cb85c"}
risk_summary.plot(
    kind="bar", ax=ax,
    color=[colors.get(r, "gray") for r in risk_summary.index],
    edgecolor="black"
)
ax.set_title("Predicted Risk Level Distribution (Test Set)")
ax.set_ylabel("Count")
ax.tick_params(axis="x", rotation=0)
plt.tight_layout()
plt.savefig(OUTPUT_DIR / "04_risk_distribution.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Saved: 04_risk_distribution.png")

"""## 📦 Step 14 — Zip All Outputs & Download

All charts, the trained model, metrics CSVs, and predictions are bundled
into a single ZIP file which is automatically downloaded.
"""

import zipfile

zip_output_path = "/content/student_engagement_outputs.zip"

with zipfile.ZipFile(zip_output_path, "w", zipfile.ZIP_DEFLATED) as zf:
    for f in sorted(OUTPUT_DIR.iterdir()):
        zf.write(f, arcname=f.name)
        print(f"   Added: {f.name}")

print(f"\n✅ Archive created: {zip_output_path}")

from google.colab import files
files.download(zip_output_path)