# -*- coding: utf-8 -*-
"""GitHUb_Repo_Source_Gode_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoGTjQJvi8upTMp3mW_gAo4LS-8rse3-

# 🔍 Source Code Analyzer — RAG-Powered GitHub Codebase Q&A

**Architecture Overview:**
1. Clone a GitHub repo
2. Index all Python files with AST-aware chunking (classes/functions kept intact)
3. Embed chunks into a FAISS vector store
4. Answer natural-language questions via RAG + LangChain (GROQ / llama-instant)
5. Serve everything through a Flask API with multi-turn chat

**Tech Stack:** LangChain · FAISS · Flask · GROQ (llama-3.1-8b-instant) · Tavily Search

> **Before running:** set the environment variables in Cell 2 or export them in your shell.

## Install Dependencies
"""

# ─────────────────────────────────────────────
#   Install all required packages
# ─────────────────────────────────────────────
import subprocess, sys

packages = [
    "langchain",
    "langchain-community",
    "langchain-groq",
    "langchain-openai",   # for OpenAI-compatible embeddings fallback
    "faiss-cpu",
    "flask",
    "flask-cors",
    "gitpython",
    "tavily-python",
    "tiktoken",
    "sentence-transformers",  # local embeddings (no OpenAI key needed)
    "huggingface-hub",
    "pydantic",
]

for pkg in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

print("✅ All packages installed successfully.")

"""##  Environment / API Keys

> **Security note:** Keys are read from environment variables. Never hard-code secrets — this notebook will not expose them in the output, and `.gitignore` should exclude any `.env` file.
"""

import os
from getpass import getpass
from google.colab import userdata

# ── Helper: load or prompt ─────────────────────
def _load_key(env_var: str, label: str) -> str:
    """Return the env var if set, otherwise prompt the user (hidden input)."""
    value = os.environ.get(env_var, "")
    if not value:
        # Try loading from Colab secrets
        try:
            value = userdata.get(env_var)
            if value:
                os.environ[env_var] = value
                print(f"✅ {env_var} loaded from Colab secrets.")
                return value
        except Exception:
            pass # If userdata.get fails or env_var not found in secrets, continue to prompt

    if not value:
        # Fallback to getpass if not found in env or secrets
        value = getpass(f"Enter {label} (input hidden): ")
        os.environ[env_var] = value
    else:
        print(f"✅ {env_var} loaded from environment.")
    return value

GROQ_API_KEY   = _load_key("GROQ_API_KEY",   "GROQ API Key")
TAVILY_API_KEY = _load_key("TAVILY_API_KEY", "Tavily API Key")

# Optional — only needed if you want OpenAI embeddings
# OPENAI_API_KEY = _load_key("OPENAI_API_KEY", "OpenAI API Key")

print("\n🔑 API keys configured. Ready to proceed.")

"""## Repository Cloner"""

# ─────────────────────────────────────────────
#   Clone a GitHub repository locally
# ─────────────────────────────────────────────
import shutil
import tempfile
from pathlib import Path
from git import Repo, InvalidGitRepositoryError

CLONE_BASE_DIR = Path(tempfile.gettempdir()) / "src_analyzer_repos"
CLONE_BASE_DIR.mkdir(parents=True, exist_ok=True)


def clone_repository(github_url: str, force_reclone: bool = False) -> Path:
    """
    Clone a public GitHub repository into a local temp directory.

    Parameters
    ----------
    github_url   : Full HTTPS URL, e.g. 'https://github.com/user/repo'
    force_reclone: Delete existing clone and re-clone from scratch

    Returns
    -------
    Path to the cloned repository root
    """
    # Derive a safe local folder name from the URL
    repo_name = github_url.rstrip("/").split("/")[-1].replace(".git", "")
    repo_path = CLONE_BASE_DIR / repo_name

    if repo_path.exists():
        if force_reclone:
            print(f"🗑  Removing existing clone at {repo_path}")
            shutil.rmtree(repo_path)
        else:
            try:
                Repo(repo_path)   # validate it's a real git repo
                print(f"✅ Repo already cloned at: {repo_path}")
                return repo_path
            except InvalidGitRepositoryError:
                shutil.rmtree(repo_path)

    print(f"⬇️  Cloning {github_url} → {repo_path} …")
    Repo.clone_from(github_url, repo_path, depth=1)   # shallow clone for speed
    print(f"✅ Clone complete: {repo_path}")
    return repo_path


# ── Quick smoke test ──────────────────────────
DEMO_REPO_URL = "https://github.com/pallets/flask"   # change to any public repo
repo_root = clone_repository(DEMO_REPO_URL)
print(f"\nRepo root: {repo_root}")

"""##  AST-Aware Python Chunker

Standard text splitters break code mid-function. This chunker uses Python's `ast` module to:
- Keep each **class** and each **function** definition as an atomic chunk
- Fall back to line-based splitting for module-level code
"""

# ─────────────────────────────────────────────
#   AST-aware code chunker
# ─────────────────────────────────────────────
import ast
import textwrap
from dataclasses import dataclass, field
from typing import List

MAX_CHUNK_CHARS = 3_000   # keep well inside token limits


@dataclass
class CodeChunk:
    """A single semantic chunk extracted from a Python source file."""
    content:   str
    file_path: str
    chunk_type: str          # 'class' | 'function' | 'module'
    name:      str = ""
    start_line: int = 0
    end_line:   int = 0
    metadata:  dict = field(default_factory=dict)


def _extract_ast_chunks(source: str, file_path: str) -> List[CodeChunk]:
    """Parse Python source with AST and yield class/function chunks."""
    chunks: List[CodeChunk] = []
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []   # not valid Python; skip silently

    lines = source.splitlines(keepends=True)

    def _extract_node(node, chunk_type: str) -> CodeChunk:
        start = node.lineno - 1          # 0-indexed
        end   = node.end_lineno          # exclusive upper bound
        snippet = "".join(lines[start:end]).strip()
        # Trim oversized chunks to MAX_CHUNK_CHARS
        if len(snippet) > MAX_CHUNK_CHARS:
            snippet = snippet[:MAX_CHUNK_CHARS] + "\n# ... [truncated]"
        return CodeChunk(
            content    = snippet,
            file_path  = file_path,
            chunk_type = chunk_type,
            name       = getattr(node, "name", ""),
            start_line = node.lineno,
            end_line   = node.end_lineno,
            metadata   = {
                "source":     file_path,
                "chunk_type": chunk_type,
                "name":       getattr(node, "name", ""),
                "start_line": node.lineno,
                "end_line":   node.end_lineno,
            },
        )

    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            chunks.append(_extract_node(node, "class"))
        elif isinstance(node, ast.FunctionDef) or isinstance(node, ast.AsyncFunctionDef):
            # Skip methods that will already be included in their parent class chunk
            # by checking if the immediate parent is a ClassDef
            chunks.append(_extract_node(node, "function"))

    return chunks


def _module_level_chunk(source: str, file_path: str) -> List[CodeChunk]:
    """Fallback: chunk module-level code by line groups."""
    chunks = []
    lines = source.splitlines()
    step  = 60   # lines per module chunk
    for i in range(0, len(lines), step):
        snippet = "\n".join(lines[i : i + step]).strip()
        if snippet:
            chunks.append(CodeChunk(
                content    = snippet,
                file_path  = file_path,
                chunk_type = "module",
                start_line = i + 1,
                end_line   = min(i + step, len(lines)),
                metadata   = {
                    "source":     file_path,
                    "chunk_type": "module",
                    "start_line": i + 1,
                },
            ))
    return chunks


def chunk_python_file(file_path: str) -> List[CodeChunk]:
    """Main entry-point: return all semantic chunks for one .py file."""
    try:
        source = Path(file_path).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return []

    ast_chunks = _extract_ast_chunks(source, file_path)
    # Always add a module-level fallback so file headers/imports are indexed
    module_chunks = _module_level_chunk(source, file_path)

    # Deduplicate by content hash (AST chunks overlap with module chunks)
    seen   = set()
    result = []
    for c in ast_chunks + module_chunks:
        h = hash(c.content)
        if h not in seen:
            seen.add(h)
            result.append(c)
    return result


def index_repository(repo_path: Path) -> List[CodeChunk]:
    """
    Walk the repo, collect every .py file, and return all code chunks.
    Skips common non-source directories (tests, migrations, venv, etc.).
    """
    SKIP_DIRS = {"__pycache__", ".git", "venv", ".venv",
                 "migrations", "node_modules", ".tox", "dist", "build"}
    all_chunks: List[CodeChunk] = []

    for py_file in repo_path.rglob("*.py"):
        if any(part in SKIP_DIRS for part in py_file.parts):
            continue
        chunks = chunk_python_file(str(py_file))
        all_chunks.extend(chunks)

    print(f"📦 Indexed {len(all_chunks)} chunks from "
          f"{len(list(repo_path.rglob('*.py')))} Python files.")
    return all_chunks


# ── Smoke test ────────────────────────────────
all_chunks = index_repository(repo_root)
if all_chunks:
    sample = all_chunks[0]
    print(f"\nSample chunk — {sample.chunk_type}: {sample.name or '(module)'}")
    print(f"File: {sample.file_path}")
    print("─" * 60)
    print(textwrap.shorten(sample.content, width=200, placeholder=" …"))

"""## Build FAISS Vector Store"""

# ─────────────────────────────────────────────
#  Embed chunks and store in FAISS
#  Uses HuggingFace sentence-transformers
#  (free, no extra API key required)
# ─────────────────────────────────────────────
import pickle
from pathlib import Path
from langchain_core.documents import Document
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

VECTORSTORE_DIR = Path(tempfile.gettempdir()) / "src_analyzer_faiss"
EMBED_MODEL     = "sentence-transformers/all-MiniLM-L6-v2"   # fast, 384-dim


def build_vector_store(
    chunks: List[CodeChunk],
    persist_dir: Path = VECTORSTORE_DIR,
    force_rebuild: bool = False,
) -> FAISS:
    """
    Convert CodeChunk list → LangChain Documents → FAISS index.
    Persists the index to disk; loads from cache on subsequent calls.
    """
    persist_dir = Path(persist_dir)
    index_file  = persist_dir / "index.faiss"

    embeddings = HuggingFaceEmbeddings(
        model_name=EMBED_MODEL,
        model_kwargs={"device": "cpu"},
        encode_kwargs={"normalize_embeddings": True},
    )

    if index_file.exists() and not force_rebuild:
        print(f"⚡ Loading cached FAISS index from {persist_dir}")
        vs = FAISS.load_local(
            str(persist_dir),
            embeddings,
            allow_dangerous_deserialization=True,
        )
        print(f"✅ Loaded. Index contains {vs.index.ntotal} vectors.")
        return vs

    # ── Convert to LangChain Documents ──────────
    docs = [
        Document(
            page_content = c.content,
            metadata     = {
                **c.metadata,
                # Relative path for cleaner display
                "display_path": str(Path(c.file_path).name),
            },
        )
        for c in chunks
        if c.content.strip()   # skip empty chunks
    ]

    print(f"🔢 Embedding {len(docs)} documents — this may take a minute …")
    vs = FAISS.from_documents(docs, embeddings)

    persist_dir.mkdir(parents=True, exist_ok=True)
    vs.save_local(str(persist_dir))
    print(f"✅ FAISS index saved → {persist_dir}  ({vs.index.ntotal} vectors)")
    return vs


vector_store = build_vector_store(all_chunks)
retriever    = vector_store.as_retriever(
    search_type="mmr",                    # Maximum Marginal Relevance — diverse results
    search_kwargs={"k": 6, "fetch_k": 20},
)
print("\n✅ Retriever ready.")

"""## GROQ LLM + Tavily Search Tool"""

# ─────────────────────────────────────────────
#   · GROQ LLM (llama-3.1-8b-instant)
#           and Tavily web-search tool
# ─────────────────────────────────────────────
from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults

# ── GROQ LLM ──────────────────────────────────
llm = ChatGroq(
    model       = "llama-3.1-8b-instant",
    temperature = 0.2,
    max_tokens  = 1_024,          # conservative — llama-instant has a 8k context
    api_key     = GROQ_API_KEY,
)

# ── Tavily search tool ─────────────────────────
# Used as a fallback when the local codebase doesn't answer the question
tavily_tool = TavilySearchResults(
    max_results      = 3,
    api_key          = TAVILY_API_KEY,
    search_depth     = "basic",
    include_answer   = True,
    include_raw_content = False,
)

print("✅ GROQ LLM and Tavily search tool initialized.")

# ── Sanity check ──────────────────────────────
test_resp = llm.invoke("Reply with exactly: LLM OK")
print(f"LLM test: {test_resp.content.strip()}")

"""## RAG Chain with Memory (LangChain v0.1)"""

import langchain
print(langchain.__version__)

!pip list | grep langchain

# =============================================================================
# BUILD COMPLETE RAG PIPELINE
# -----------------------------------------------------------------------------
# Components:
#   1. Conversational Memory (last 6 turns)
#   2. Follow-up Question Rewriting
#   3. Retrieval-Augmented Generation (RAG)
#   4. Source Document Tracking
#   5. Tavily Web Search Fallback
#
# Compatible With:
#   - LangChain 1.2.x
#   - langchain-classic 1.x
# =============================================================================

# =============================================================================
# IMPORTS
# =============================================================================

# Legacy memory and conversational chain support
from langchain_classic.memory import ConversationBufferWindowMemory
from langchain_classic.chains import ConversationalRetrievalChain

# Prompt utilities
from langchain_core.prompts import (
    PromptTemplate,
    ChatPromptTemplate,
)

from langchain_core.prompts.chat import (
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate,
)

# =============================================================================
# CONVERSATION MEMORY
# -----------------------------------------------------------------------------
# Maintains the last 6 conversation turns.
#
# Example:
#   User: Explain the authentication service.
#   User: What methods does it expose?
#
# The second question automatically receives context from the first.
# =============================================================================

memory = ConversationBufferWindowMemory(
    k=6,                          # Number of recent interactions retained
    memory_key="chat_history",    # Variable name injected into prompts
    return_messages=True,         # Return structured chat messages
    output_key="answer",          # Expected chain output field
)

# =============================================================================
# SYSTEM PROMPT
# -----------------------------------------------------------------------------
# Governs answer generation.
#
# Rules:
#   • Answer ONLY from retrieved repository context.
#   • Reference filenames/functions/classes when available.
#   • Avoid hallucinations.
#   • Explicitly acknowledge missing information.
# =============================================================================

SYSTEM_TEMPLATE = """\
You are a senior software engineer and code reviewer with deep expertise in Python.

You are analysing a GitHub repository. Answer the developer's question using ONLY
the retrieved source-code context below.

Be precise, reference specific file names and function/class names when relevant,
and keep answers concise.

If the context does not contain enough information to answer, say so clearly and
suggest where the developer should look next.

── Retrieved Context ────────────────────────────
{context}
─────────────────────────────────────────────────
"""

# Chat-style QA prompt
QA_PROMPT = ChatPromptTemplate.from_messages(
    [
        SystemMessagePromptTemplate.from_template(SYSTEM_TEMPLATE),
        HumanMessagePromptTemplate.from_template("{question}"),
    ]
)

# =============================================================================
# QUESTION CONDENSATION PROMPT
# -----------------------------------------------------------------------------
# Converts follow-up questions into standalone questions.
#
# Example:
#
#   User: Explain the FastAPI router.
#   User: What middleware does it use?
#
# Rewritten:
#
#   What middleware does the FastAPI router use?
#
# This improves retrieval quality.
# =============================================================================

CONDENSE_TEMPLATE = """\
Given the conversation history and the follow-up question, rephrase the follow-up
question into a standalone question that captures all necessary context.

Return ONLY the standalone question, nothing else.

Chat history:
{chat_history}

Follow-up question: {question}

Standalone question:
"""

CONDENSE_PROMPT = PromptTemplate.from_template(
    CONDENSE_TEMPLATE
)

# =============================================================================
# CONVERSATIONAL RETRIEVAL CHAIN
# -----------------------------------------------------------------------------
# Workflow:
#
#   User Question
#          ↓
#   Condense Question
#          ↓
#   Retrieve Relevant Chunks
#          ↓
#   Inject Context Into Prompt
#          ↓
#   Generate Answer
#          ↓
#   Return Source Documents
#
# Memory is automatically incorporated into retrieval.
# =============================================================================

rag_chain = ConversationalRetrievalChain.from_llm(
    llm=llm,
    retriever=retriever,
    memory=memory,

    # Rephrase follow-up questions
    condense_question_prompt=CONDENSE_PROMPT,

    # Custom QA prompt
    combine_docs_chain_kwargs={
        "prompt": QA_PROMPT
    },

    # Return retrieved documents
    return_source_documents=True,

    # Disable chain debug logs
    verbose=False,
)

print("✅ RAG chain with memory is ready.")

# =============================================================================
# QUESTION ANSWERING FUNCTION
# -----------------------------------------------------------------------------
# Executes:
#   1. Retrieval-Augmented Generation
#   2. Source Extraction
#   3. Low-Confidence Detection
#   4. Optional Tavily Search Fallback
#
# Returns:
#   {
#       "answer": str,
#       "sources": list[str],
#       "tavily_results": list | None
#   }
# =============================================================================

def ask(
    question: str,
    use_tavily_fallback: bool = True,
) -> dict:
    """
    Query the indexed GitHub repository.

    Parameters
    ----------
    question : str
        User question about the repository.

    use_tavily_fallback : bool
        Trigger Tavily search when the generated answer
        appears low confidence.

    Returns
    -------
    dict
        {
            "answer": str,
            "sources": list[str],
            "tavily_results": list | None
        }
    """

    # -------------------------------------------------------------------------
    # Run RAG pipeline
    # -------------------------------------------------------------------------
    result = rag_chain(
        {"question": question}
    )

    answer = result["answer"]

    # -------------------------------------------------------------------------
    # Extract unique source file paths
    # -------------------------------------------------------------------------
    sources = list(
        {
            doc.metadata.get("source", "unknown")
            for doc in result.get("source_documents", [])
        }
    )

    # -------------------------------------------------------------------------
    # Confidence evaluation
    # -------------------------------------------------------------------------
    tavily_results = None

    LOW_CONFIDENCE_PHRASES = [
        "i don't know",
        "not found",
        "no information",
        "cannot find",
        "doesn't contain",
        "does not contain",
    ]

    low_confidence_detected = any(
        phrase in answer.lower()
        for phrase in LOW_CONFIDENCE_PHRASES
    )

    # -------------------------------------------------------------------------
    # Tavily fallback search
    # -------------------------------------------------------------------------
    if use_tavily_fallback and low_confidence_detected:

        print(
            "🌐 Low-confidence answer detected — "
            "searching the web via Tavily..."
        )

        try:
            tavily_results = tavily_tool.run(
                question
            )

        except Exception as e:
            tavily_results = [
                {
                    "error": str(e)
                }
            ]

    # -------------------------------------------------------------------------
    # Structured response
    # -------------------------------------------------------------------------
    return {
        "answer": answer,
        "sources": sources,
        "tavily_results": tavily_results,
    }

# =============================================================================
# QUICK VALIDATION TEST
# -----------------------------------------------------------------------------
# Smoke test:
#   • Retrieval works
#   • Memory works
#   • Sources are returned
# =============================================================================

demo_result = ask(
    "What is the main entry point of this project?"
)

print("\n📝 Answer:\n")
print(demo_result["answer"])

print("\n📂 Sources:")
print(demo_result["sources"][:3])

# Question 1
result1 = ask("What are the main modules or components in this repository?")

print("\n📝 Answer:\n")
print(result1["answer"])

print("\n📂 Sources:")
print(result1["sources"][:5])

# Question 2 (tests conversational memory)
result2 = ask("Which of those components appears to be the most important and why?")

print("\n📝 Answer:\n")
print(result2["answer"])

print("\n📂 Sources:")
print(result2["sources"][:5])

# Question 3
result3 = ask("Tell me about the main API module.")

print(result3["answer"])

# Question 4 (should use memory automatically)
result4 = ask("What methods or endpoints does it expose?")

print(result4["answer"])

print("\n===== MEMORY CONTENT =====\n")

for i, msg in enumerate(memory.chat_memory.messages):
    print(f"{i+1}. {type(msg).__name__}")
    print(msg.content[:500])
    print("-" * 80)

"""##  Multi-Turn Interactive Chat"""

# ─────────────────────────────────────────────
#  · Interactive multi-turn chat loop
#           (runs inside the notebook)
#  Type 'exit', 'quit', or 'q' to stop.
#  Type 'reset' to clear conversation memory.
# ─────────────────────────────────────────────

print("=" * 60)
print(" Source Code Analyzer — Interactive Chat")
print(f" Repo : {DEMO_REPO_URL}")
print(" Type 'exit' to quit | 'reset' to clear memory")
print("=" * 60)

while True:
    try:
        user_input = input("\n🧑 You: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("\n👋 Session ended.")
        break

    if not user_input:
        continue

    if user_input.lower() in {"exit", "quit", "q"}:
        print("👋 Goodbye!")
        break

    if user_input.lower() == "reset":
        memory.clear()
        print("🔄 Memory cleared. Starting fresh conversation.")
        continue

    result = ask(user_input)

    print(f"\n🤖 Assistant:\n{result['answer']}")

    if result["sources"]:
        print("\n📂 Sources used:")
        for s in result["sources"][:4]:
            print(f"   • {s}")

    if result["tavily_results"]:
        print("\n🌐 Web search results (Tavily fallback):")
        for r in result["tavily_results"][:2]:
            print(f"   • {r.get('url', '')} — {r.get('content', '')[:120]}")

"""## Cell 9 — Flask REST API

Run this cell to start the Flask server.  
The server runs **in the background** so the notebook remains interactive.

| Endpoint | Method | Description |
|---|---|---|
| `/api/load` | POST | Clone repo and build index |
| `/api/chat` | POST | Ask a question |
| `/api/reset` | POST | Clear conversation memory |
| `/api/health` | GET  | Liveness check |
"""

# ─────────────────────────────────────────────
# Flask REST API
# ─────────────────────────────────────────────
import threading
import json
from flask import Flask, request, jsonify
from flask_cors import CORS

# Correct import for ConversationBufferWindowMemory
from langchain_classic.memory import ConversationBufferWindowMemory

app = Flask(__name__)
CORS(app)  # allow cross-origin requests from any front-end

# ── In-memory state (one repo at a time) ──────
_state = {
    "repo_url":     None,
    "repo_root":    None,
    "vector_store": None,
    "retriever":    None,
    "rag_chain":    None,
    "memory":       None,
}


def _build_chain_for_state():
    """Rebuild the RAG chain from current _state vector store."""
    mem = ConversationBufferWindowMemory(
        k=6, memory_key="chat_history",
        return_messages=True, output_key="answer",
    )
    retr = _state["vector_store"].as_retriever(
        search_type="mmr",
        search_kwargs={"k": 6, "fetch_k": 20},
    )
    chain = ConversationalRetrievalChain.from_llm(
        llm                       = llm,
        retriever                 = retr,
        memory                    = mem,
        condense_question_prompt  = CONDENSE_PROMPT,
        combine_docs_chain_kwargs = {"prompt": QA_PROMPT},
        return_source_documents   = True,
        verbose                   = False,
    )
    _state["memory"]    = mem
    _state["retriever"] = retr
    _state["rag_chain"] = chain


# ────────────────────────────────────────────
#  Routes
# ────────────────────────────────────────────

@app.route("/api/health", methods=["GET"])
def health():
    """Liveness check."""
    return jsonify({
        "status":   "ok",
        "repo_url": _state["repo_url"],
        "indexed":  _state["vector_store"] is not None,
    })


@app.route("/api/load", methods=["POST"])
def load_repo():
    """
    Clone a GitHub repository and build the FAISS index.

    Body (JSON):
        repo_url      : str  — GitHub HTTPS URL
        force_rebuild : bool — optional, default false

    Returns:
        {status, repo_url, chunk_count, message}
    """
    data = request.get_json(force=True)
    repo_url = (data or {}).get("repo_url", "").strip()
    force_rb = bool((data or {}).get("force_rebuild", False))

    if not repo_url:
        return jsonify({"error": "'repo_url' is required"}), 400

    try:
        root   = clone_repository(repo_url, force_reclone=force_rb)
        chunks = index_repository(root)
        if not chunks:
            return jsonify({"error": "No Python files found in repository."}), 422

        vs_dir = VECTORSTORE_DIR / root.name
        vs     = build_vector_store(chunks, persist_dir=vs_dir, force_rebuild=force_rb)

        _state["repo_url"]     = repo_url
        _state["repo_root"]    = root
        _state["vector_store"] = vs
        _build_chain_for_state()

        return jsonify({
            "status":      "ok",
            "repo_url":    repo_url,
            "chunk_count": len(chunks),
            "message":     f"Repository indexed successfully ({len(chunks)} chunks).",
        })
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.route("/api/chat", methods=["POST"])
def chat():
    """
    Ask a natural-language question about the indexed codebase.

    Body (JSON):
        question : str  — developer's question
        tavily   : bool — optional, enable web fallback (default true)

    Returns:
        {answer, sources, tavily_results}
    """
    if _state["rag_chain"] is None:
        return jsonify({"error": "No repository loaded. POST to /api/load first."}), 400

    data     = request.get_json(force=True)
    question = (data or {}).get("question", "").strip()
    use_tav  = bool((data or {}).get("tavily", True))

    if not question:
        return jsonify({"error": "'question' is required"}), 400

    try:
        result = _state["rag_chain"]({"question": question})
        answer  = result["answer"]
        sources = list({
            doc.metadata.get("source", "unknown")
            for doc in result.get("source_documents", [])
        })

        tavily_results = None
        LOW = ["i don't know", "not found", "no information",
               "cannot find", "doesn't contain", "does not contain"]
        if use_tav and any(p in answer.lower() for p in LOW):
            try:
                tavily_results = tavily_tool.run(question)
            except Exception:
                pass

        return jsonify({
            "answer":         answer,
            "sources":        sources,
            "tavily_results": tavily_results,
        })
    except Exception as exc:
        return jsonify({"error": str(exc)}), 500


@app.route("/api/reset", methods=["POST"])
def reset_memory():
    """
    Clear the conversation memory (keep the vector store).
    """
    if _state["memory"] is not None:
        _state["memory"].clear()
        return jsonify({"status": "ok", "message": "Conversation memory cleared."})
    return jsonify({"status": "ok", "message": "Nothing to clear."})


# ── Start Flask in a daemon thread ────────────
FLASK_PORT = 5050

def _run_flask():
    app.run(host="0.0.0.0", port=FLASK_PORT, debug=False, use_reloader=False)

flask_thread = threading.Thread(target=_run_flask, daemon=True)
flask_thread.start()

print(f"✅ Flask API running at http://localhost:{FLASK_PORT}")
print("   Endpoints:")
print(f"   • GET  http://localhost:{FLASK_PORT}/api/health")
print(f"   • POST http://localhost:{FLASK_PORT}/api/load")
print(f"   • POST http://localhost:{FLASK_PORT}/api/chat")
print(f"   • POST http://localhost:{FLASK_PORT}/api/reset")

"""## Test the  API (from within the notebook)"""

# ─────────────────────────────────────────────
#   End-to-end API test
#            Uses the 'requests' library to
#            hit the running Flask server.
# ─────────────────────────────────────────────
import time
import requests as req_lib

BASE = f"http://localhost:{FLASK_PORT}"
time.sleep(1)   # give Flask a moment to fully start

# ── 1. Health check ───────────────────────────
r = req_lib.get(f"{BASE}/api/health")
print("Health:", r.json())

# ── 2. Load a repository ─────────────────────
print("\n⬇️  Loading repo via API (reuses local clone cache) …")
r = req_lib.post(f"{BASE}/api/load", json={"repo_url": DEMO_REPO_URL})
print("Load response:", json.dumps(r.json(), indent=2))

# ── 3. First question ─────────────────────────
Q1 = "How does Flask handle request routing?"
print(f"\n🧑 Q1: {Q1}")
r = req_lib.post(f"{BASE}/api/chat", json={"question": Q1})
resp = r.json()
print("🤖 Answer:", resp["answer"][:500])
print("📂 Sources:", resp["sources"][:3])

# ── 4. Follow-up (tests memory) ───────────────
Q2 = "Can you show an example of that from the code?"
print(f"\n🧑 Q2 (follow-up): {Q2}")
r = req_lib.post(f"{BASE}/api/chat", json={"question": Q2})
resp = r.json()
print("🤖 Answer:", resp["answer"][:500])

# ── 5. Reset memory ───────────────────────────
print("\n🔄 Resetting memory …")
r = req_lib.post(f"{BASE}/api/reset")
print(r.json())

print("\n✅ All API tests passed.")

"""

```
# This is formatted as code
```

## — Minimal Web UI (served by Flask)"""

# ─────────────────────────────────────────────
#  Serve a minimal HTML chat UI
#            via Flask at /
#  Access: http://localhost:5050
# ─────────────────────────────────────────────
from flask import Response

HTML_UI = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Source Code Analyzer</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', system-ui, sans-serif;
           background: #0f1117; color: #e2e8f0; min-height: 100vh;
           display: flex; flex-direction: column; align-items: center;
           padding: 2rem 1rem; }
    h1   { font-size: 1.8rem; margin-bottom: 0.3rem;
           background: linear-gradient(90deg,#60a5fa,#a78bfa);
           -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
    p.sub { color:#94a3b8; margin-bottom:1.5rem; font-size:0.9rem; }
    .card { background:#1e2330; border:1px solid #2d3748; border-radius:12px;
            padding:1.2rem; width:100%; max-width:760px; margin-bottom:1rem; }
    .row  { display:flex; gap:0.6rem; }
    input, textarea {
      flex:1; background:#0f1117; border:1px solid #2d3748; border-radius:8px;
      color:#e2e8f0; padding:0.6rem 0.9rem; font-size:0.95rem; outline:none;
    }
    input:focus, textarea:focus { border-color:#60a5fa; }
    textarea { resize:vertical; min-height:72px; }
    button {
      background:linear-gradient(135deg,#3b82f6,#7c3aed); color:#fff;
      border:none; border-radius:8px; padding:0.6rem 1.3rem;
      cursor:pointer; font-size:0.95rem; white-space:nowrap;
    }
    button:disabled { opacity:0.45; cursor:not-allowed; }
    #chat { max-height:440px; overflow-y:auto; display:flex;
            flex-direction:column; gap:0.8rem; margin-bottom:1rem; }
    .msg  { padding:0.8rem 1rem; border-radius:10px; max-width:92%; line-height:1.55;
            font-size:0.9rem; white-space:pre-wrap; word-break:break-word; }
    .user { background:#1d3a5f; align-self:flex-end; }
    .bot  { background:#1a2535; border:1px solid #2d3748; align-self:flex-start; }
    .src  { font-size:0.75rem; color:#64748b; margin-top:0.4rem; }
    #status { color:#facc15; font-size:0.82rem; margin-top:0.5rem; min-height:1.2rem; }
  </style>
</head>
<body>
  <h1>🔍 Source Code Analyzer</h1>
  <p class="sub">Powered by LangChain · FAISS · GROQ llama-3.1-8b-instant · Tavily</p>

  <div class="card">
    <div class="row">
      <input id="repoUrl" placeholder="https://github.com/user/repo" />
      <button id="loadBtn" onclick="loadRepo()">Load Repo</button>
    </div>
    <div id="status"></div>
  </div>

  <div class="card" style="flex:1">
    <div id="chat"></div>
    <div class="row">
      <textarea id="question" placeholder="Ask about the codebase …" rows="2"
        onkeydown="if(event.ctrlKey&&event.key==='Enter')sendMsg()"></textarea>
      <div style="display:flex;flex-direction:column;gap:0.4rem">
        <button id="askBtn" onclick="sendMsg()">Ask ↩</button>
        <button onclick="resetMem()" style="background:#374151;font-size:0.8rem">Reset</button>
      </div>
    </div>
    <p style="color:#475569;font-size:0.75rem;margin-top:0.5rem">Ctrl+Enter to send</p>
  </div>

<script>
const BASE = '';
function status(msg, color='#facc15'){
  const el=document.getElementById('status');
  el.style.color=color; el.textContent=msg;
}
function appendMsg(role, text, sources){
  const chat=document.getElementById('chat');
  const div=document.createElement('div');
  div.className='msg '+(role==='user'?'user':'bot');
  div.textContent=text;
  if(sources&&sources.length){
    const s=document.createElement('div');
    s.className='src';
    s.textContent='Sources: '+sources.slice(0,3).map(p=>p.split('/').pop()).join(', ');
    div.appendChild(s);
  }
  chat.appendChild(div);
  chat.scrollTop=chat.scrollHeight;
}
async function loadRepo(){
  const url=document.getElementById('repoUrl').value.trim();
  if(!url){status('Please enter a repo URL.');return;}
  document.getElementById('loadBtn').disabled=true;
  status('Cloning and indexing … (this may take 30–90 s)');
  try{
    const r=await fetch(BASE+'/api/load',{
      method:'POST', headers:{'Content-Type':'application/json'},
      body:JSON.stringify({repo_url:url})
    });
    const d=await r.json();
    if(d.error){status('Error: '+d.error,'#f87171');}
    else{status('✅ '+d.message,'#4ade80');}
  }catch(e){status('Request failed: '+e,'#f87171');}
  document.getElementById('loadBtn').disabled=false;
}
async function sendMsg(){
  const q=document.getElementById('question').value.trim();
  if(!q)return;
  document.getElementById('question').value='';
  appendMsg('user',q);
  document.getElementById('askBtn').disabled=true;
  try{
    const r=await fetch(BASE+'/api/chat',{
      method:'POST', headers:{'Content-Type':'application/json'},
      body:JSON.stringify({question:q})
    });
    const d=await r.json();
    if(d.error){appendMsg('bot','⚠️ '+d.error);}
    else{appendMsg('bot',d.answer,d.sources);}
  }catch(e){appendMsg('bot','Request failed: '+e);}
  document.getElementById('askBtn').disabled=false;
}
async function resetMem(){
  await fetch(BASE+'/api/reset',{method:'POST'});
  document.getElementById('chat').innerHTML='';
  status('Memory cleared.','#94a3b8');
}
</script>
</body>
</html>
"""

@app.route("/")
def ui():
    return Response(HTML_UI, mimetype="text/html")

print(f"🌐 Web UI available at http://localhost:{FLASK_PORT}")

"""##  Checkpoint Summary & Usage Guide

```
┌─────────────────────────────────────────────────────────────────────┐
│              SOURCE CODE ANALYZER — CHECKPOINT SUMMARY              │
├──────────────┬──────────────────────────────────────────────────────┤
│ Cell 1       │ Package installation                                  │
│ Cell 2       │ API key configuration (env vars / getpass)            │
│ Cell 3       │ GitHub repo cloner (shallow, cached)                  │
│ Cell 4       │ AST-aware Python chunker + repo indexer               │
│ Cell 5       │ FAISS vector store (HuggingFace embeddings, cached)   │
│ Cell 6       │ GROQ LLM + Tavily search tool                         │
│ Cell 7       │ ConversationalRetrievalChain with memory              │
│ Cell 8       │ Interactive multi-turn chat (notebook REPL)           │
│ Cell 9       │ Flask REST API (4 endpoints)                           │
│ Cell 10      │ End-to-end API test                                    │
│ Cell 11      │ Minimal web UI (served by Flask)                       │
│ Cell 12      │ This summary                                           │
└──────────────┴──────────────────────────────────────────────────────┘
```

### Git Safety
This notebook **never stores API keys** in cell outputs — they are loaded from environment variables or via hidden `getpass()` prompts, and outputs should be cleared before committing.

Add this to your `.gitignore`:
```
.env
*.env
__pycache__/
*.pyc
```

### Caching
- Cloned repos are cached in `$TMPDIR/src_analyzer_repos/`
- FAISS indexes are cached in `$TMPDIR/src_analyzer_faiss/`
- Pass `force_rebuild=True` to `/api/load` to invalidate caches

### Token Budget (GROQ llama-3.1-8b-instant)
- Context window: **128k tokens** input
- `max_tokens=1024` for responses keeps costs low
- Each chunk is capped at **3000 chars** (~750 tokens) before embedding
- MMR retrieval returns **6 chunks** per query (~4500 tokens of context)
"""

# ─────────────────────────────────────────────
#   · Final status checkpoint
# ─────────────────────────────────────────────
import sys

checks = {
    "GROQ_API_KEY set"      : bool(os.environ.get("GROQ_API_KEY")),
    "TAVILY_API_KEY set"    : bool(os.environ.get("TAVILY_API_KEY")),
    "Repo cloned"           : repo_root is not None and repo_root.exists(),
    "Chunks indexed"        : len(all_chunks) > 0,
    "Vector store built"    : vector_store is not None,
    "RAG chain ready"       : rag_chain is not None,
    "Flask server running"  : flask_thread.is_alive(),
}

print("\n=== SYSTEM CHECKPOINT ===")
all_ok = True
for label, ok in checks.items():
    icon = "✅" if ok else "❌"
    print(f"  {icon}  {label}")
    if not ok:
        all_ok = False

if all_ok:
    print(f"\n🚀 Everything is ready!")
    print(f"   Flask API : http://localhost:{FLASK_PORT}/api")
    print(f"   Web UI    : http://localhost:{FLASK_PORT}")
    print(f"   Repo      : {DEMO_REPO_URL}")
    print(f"   Chunks    : {len(all_chunks)}")
    print(f"   Vectors   : {vector_store.index.ntotal}")
else:
    print("\n⚠️  Some checks failed — re-run the indicated cells.")