# -*- coding: utf-8 -*-
"""StoryForge_YouTube_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LfFDZORscTAmNoRSZCvdu1l8cj9OwFlp

# 🎬 StoryForge Agent — YouTube Content Creation Pipeline
### LangChain + Groq (LLaMA) + Tavily + ChromaDB | Full Colab Notebook

**Project structure is preserved exactly as in the original source.**  
All `.py` utility files are written to disk inside the notebook before use.

---
**Pipeline overview:**
1. Query validation & transformation  
2. Tavily real-time web search  
3. AI-powered summarisation (Groq / LLaMA)  
4. Video-script generation  
5. Pydantic request/response modelling  
6. Mem0 memory layer (ChromaDB — free, local)  
7. Structured logging  
8. Phase outputs saved → final ZIP download

## 📦 Step 1 — Install Dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# Install all required packages.
# LangChain ≥ 1.2, Groq provider, Tavily, Mem0, Pydantic v2, ChromaDB (free local vector DB).
# %pip install -q \
    langchain\
    langchain-groq\
    langchain-community \
    langchain-core\
    tavily-python\
    mem0ai\
    chromadb \
    pydantic[email] \
    python-dotenv>\
    ipywidgets

print("✅ All packages installed.")

"""## 🔑 Step 2 — Load API Keys from Colab Secrets"""

import os

# Retrieve API keys stored in Colab secrets (Colab → Secrets panel).
# Keys required: GROQ_API_KEY, TAVILY_API_KEY
try:
    from google.colab import userdata
    os.environ["GROQ_API_KEY"]   = userdata.get("GROQ_API_KEY")
    os.environ["TAVILY_API_KEY"] = userdata.get("TAVILY_API_KEY")
    print("✅ API keys loaded from Colab secrets.")
except Exception:
    # Fallback: set manually if not using Colab secrets
    # os.environ["GROQ_API_KEY"]   = "your-groq-key-here"
    # os.environ["TAVILY_API_KEY"] = "your-tavily-key-here"
    print("⚠️  Could not read Colab secrets — set os.environ keys manually above.")

"""## 🗂️ Step 3 — Create Project Directory Structure"""

import os, pathlib

# Replicate the original project folder layout on disk so all imports resolve.
BASE   = pathlib.Path("storyforge_agent")
UTILS  = BASE / "utilities"
OUTPUT = BASE / "outputs"

for d in [BASE, UTILS, OUTPUT]:
    d.mkdir(parents=True, exist_ok=True)

print("Directory tree:")
for p in sorted(BASE.rglob("*")):
    print(" ", p)
print("✅ Project structure ready.")

"""## 💾 Step 4 — Write All `.py` Source Files to Disk
> Every file matches the path in the original project archive.
"""

# ── utilities/pydantic_models.py ──────────────────────────────────────────────
# Pydantic v2 request/response models used by the StoryForge pipeline.

pydantic_models_src = '''
from pydantic import BaseModel, EmailStr, Field, field_validator
from datetime import datetime
from typing import Optional, List


class SearchRequest(BaseModel):
    """Validates incoming search requests from users."""
    user_id: str = Field(..., min_length=3, max_length=50)
    email: EmailStr
    query: str = Field(..., min_length=1, max_length=200)
    tags: Optional[List[str]] = Field(default_factory=list)

    @field_validator("query")
    def query_must_not_be_empty(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("Query must not be empty or whitespace")
        return value.strip()


class SearchResponse(BaseModel):
    """Structured response returned after processing a search request."""
    status: str
    message: str
    result_count: int = Field(0, ge=0)
    results: List[dict] = Field(default_factory=list)
    processed_at: datetime = Field(default_factory=datetime.utcnow)


def build_search_response(request: SearchRequest) -> SearchResponse:
    """Build a demo SearchResponse from a validated SearchRequest."""
    example_results = [{"id": 1, "title": "Example item", "query": request.query}]
    return SearchResponse(
        status="success",
        message=f"Search completed for user {request.user_id}",
        result_count=len(example_results),
        results=example_results,
    )


def demo() -> None:
    payload = {
        "user_id": "user123",
        "email": "user@example.com",
        "query": "search for utilities",
        "tags": ["example", "demo"],
    }
    req = SearchRequest(**payload)
    resp = build_search_response(req)
    print("Request:", req.model_dump_json(indent=2))
    print("Response:", resp.model_dump_json(indent=2))
'''

with open("storyforge_agent/utilities/pydantic_models.py", "w") as f:
    f.write(pydantic_models_src)
print("✅ utilities/pydantic_models.py written.")

# ── utilities/query_validation_transformation.py ──────────────────────────────
# Validates and normalises raw user queries before sending to the LLM/search.

query_validation_src = '''
import re
from typing import Dict

# Only alphanumerics, whitespace, and safe punctuation are allowed.
ALLOWED_QUERY_PATTERN = re.compile(r"^[a-zA-Z0-9\\s?@#\\-_.,\'()]+$")

# Stop-words stripped during normalisation.
STOP_WORDS = {"the", "is", "and", "or", "for", "a", "an", "to"}

# Simple synonym map to reduce query variants.
SYNONYMS = {
    "buy": "purchase",
    "find": "search",
    "latest": "recent",
}


def validate_query(query: str) -> bool:
    """Raise ValueError for blank or unsafe queries."""
    if not query or len(query.strip()) < 3:
        raise ValueError("Query must be at least 3 characters long.")
    if not ALLOWED_QUERY_PATTERN.match(query):
        raise ValueError("Query contains invalid characters.")
    return True


def transform_query(query: str) -> Dict[str, str]:
    """Normalise, remove stop-words, apply synonyms, return structured dict."""
    normalized = query.strip().lower()
    normalized = re.sub(r"\\s+", " ", normalized)
    tokens = normalized.split()
    tokens = [SYNONYMS.get(t, t) for t in tokens if t not in STOP_WORDS]
    cleaned = " ".join(tokens)
    return {
        "original": query,
        "normalized": normalized,
        "cleaned": cleaned,
        "signature": cleaned.replace(" ", "_"),
    }


def handle_query(query: str) -> Dict[str, str]:
    """Public entry-point: validate then transform a query."""
    validate_query(query)
    return transform_query(query)
'''

with open("storyforge_agent/utilities/query_validation_transformation.py", "w") as f:
    f.write(query_validation_src)
print("✅ utilities/query_validation_transformation.py written.")

# ── utilities/logging_example.py ──────────────────────────────────────────────
# Dual-handler (stdout + file) logger used across the project.

logging_src = '''
import logging
import sys


def get_app_logger(name: str = __name__) -> logging.Logger:
    """Return a named logger with console (INFO) and file (DEBUG) handlers."""
    logger = logging.getLogger(name)
    if logger.handlers:
        return logger  # avoid duplicate handlers on re-import

    logger.setLevel(logging.DEBUG)

    # Console handler — shows INFO and above in stdout.
    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.INFO)
    ch.setFormatter(logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))

    # File handler — captures DEBUG and above for traceability.
    fh = logging.FileHandler("storyforge_agent/outputs/storyforge.log", encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(logging.Formatter("%(asctime)s | %(levelname)s | %(name)s | %(message)s"))

    logger.addHandler(ch)
    logger.addHandler(fh)
    logger.propagate = False
    return logger


def run_logging_demo() -> None:
    """Exercise every log level to verify handler wiring."""
    logger = get_app_logger("utility_logger")
    logger.debug("Debug payload: %s", {"step": 1, "status": "starting"})
    logger.info("Application example started.")
    logger.warning("Example warning from logging utility.")
    try:
        _ = 10 / 0
    except ZeroDivisionError:
        logger.exception("Caught ZeroDivisionError in logging demo.")
    logger.info("Logging demo finished.")
'''

with open("storyforge_agent/utilities/logging_example.py", "w") as f:
    f.write(logging_src)
print("✅ utilities/logging_example.py written.")

# ── utilities/mem0_example.py ──────────────────────────────────────────────────
# Mem0 memory layer backed by ChromaDB (free, fully local — no paid service).
# Replaces the original OpenAI LLM config with Groq/LLaMA for zero-cost usage.

mem0_src = '''
import os
from mem0 import Memory


def run_observability_demo():
    """
    Demonstrate Mem0 add / update / history / search using:
      - vector store : ChromaDB (local)
      - LLM          : Groq  llama-3.1-8b-instant  (free tier)
    """
    # Remove any stale SSL env var that breaks ChromaDB on some runtimes.
    os.environ.pop("SSL_CERT_FILE", None)

    config = {
        "vector_store": {
            "provider": "chroma",
            "config": {
                "collection_name": "storyforge_demo",
                "path": "storyforge_agent/outputs/mem0_db",
            },
        },
        "llm": {
            "provider": "groq",
            "config": {
                "model": "llama-3.1-8b-instant",
                "temperature": 0,
                "groq_api_key": os.environ.get("GROQ_API_KEY"),
            },
        },
        "embedder": {
            "provider": "huggingface",
            "config": {"model": "multi-qa-MiniLM-L6-cos-v1"},
        },
    }

    m = Memory.from_config(config)
    user_id = "storyforge_user_001"

    print("\n--- [1] Storing initial preference ---")
    result = m.add("I prefer using FastAPI and AWS.", user_id=user_id)

    # Robustly extract the memory ID regardless of result shape.
    mem_id = None
    if isinstance(result, list) and result:
        mem_id = result[0].get("id")
    elif isinstance(result, dict):
        for key in ("results", "memories"):
            lst = result.get(key, [])
            if lst:
                mem_id = lst[0].get("id")
                break

    print("--- [2] Updating preference ---")
    m.add("Actually, I moved my projects to Google Cloud.", user_id=user_id)

    print("\n--- [3] Memory history ---")
    if mem_id:
        for entry in m.history(memory_id=mem_id):
            old = entry.get("old_memory") or entry.get("old_value") or "Initial"
            new = entry.get("memory") or entry.get("new_value")
            print(f"  Event: {entry.get(\'event\')}  |  {old!r} → {new!r}")
    else:
        print("  (ID not captured — check outputs/mem0_db/)")

    print("\n--- [4] Search final state ---")
    sr = m.search("What is my deployment preference?", filters={"user_id": user_id})
    memories = sr.get("results") if isinstance(sr, dict) else sr
    for r in (memories or []):
        val = r.get("memory") or r.get("payload", {}).get("value")
        print(f"  Memory: {val!r}  (score={r.get(\'score\')})")
'''

with open("storyforge_agent/utilities/mem0_example.py", "w") as f:
    f.write(mem0_src)
print("✅ utilities/mem0_example.py written.")

# Create __init__.py files so the directories are proper Python packages.
for path in [
    "storyforge_agent/__init__.py",
    "storyforge_agent/utilities/__init__.py",
]:
    with open(path, "w") as f:
        f.write("")
print("✅ __init__.py files created.")

# ── main.py ───────────────────────────────────────────────────────────────────
main_src = '''
def main():
    """Project entry-point placeholder."""
    print("Hello from StoryForge project!")

if __name__ == "__main__":
    main()
'''
with open("storyforge_agent/main.py", "w") as f:
    f.write(main_src)
print("✅ main.py written.")

import os
import sys
from typing import Optional

# LangChain \u2265 1.2 imports (new-style: langchain-groq, langchain-core)
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from tavily import TavilyClient

# \u2500\u2500 Model configuration \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n# llama-3.1-8b-instant  : low latency, generous free-tier token allowance
# llama-3.3-70b-versatile: higher quality, used when deep reasoning is needed
MODEL_INSTANT    = "llama-3.1-8b-instant"
MODEL_VERSATILE  = "llama-3.3-70b-versatile"

# Token budgets chosen conservatively to stay within Groq free-tier limits.
MAX_TOKENS_SUMMARY = 512   # ~400 words output
MAX_TOKENS_SCRIPT  = 300   # ~120-word video script


def _get_llm(model: str, max_tokens: int) -> ChatGroq:
    """Initialise a ChatGroq LLM with the given model and token ceiling."""
    return ChatGroq(
        model=model,
        temperature=0.7,
        max_tokens=max_tokens,
        api_key=os.environ.get("GROQ_API_KEY"),
    )


def _get_tavily() -> TavilyClient:
    """Return a configured Tavily search client."""
    return TavilyClient(api_key=os.environ.get("TAVILY_API_KEY"))


# \u2500\u2500 Phase 1: Real-time web research \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\ndef get_realtime_info(query: str) -> Optional[str]:
    """
    Search the web with Tavily, then summarise results using LLaMA-instant.
    Returns a ~200-word human-readable summary or None on failure.
    """
    tavily = _get_tavily()
    try:
        resp = tavily.search(query=query, max_results=3, topic="general")
    except Exception as exc:
        print(f"[Tavily] search error: {exc}", file=sys.stderr)
        return None

    # Build a compact context string from search snippets.
    if resp and resp.get("results"):
        parts = []
        for r in resp["results"]:
            title   = r.get("title", "")
            snippet = r.get("snippet") or r.get("content", "")[:300]
            url     = r.get("url", "")
            # Original: parts.append(f"Title: {title}\nSnippet: {snippet}\nURL: {url}")
            # Modified to avoid potential f-string truncation issues when written to file
            parts.append(f"Title: {title}" + f"\nSnippet: {snippet}" + f"\nURL: {url}")
        source_info = "\n---\n".join(parts)
    else:
        source_info = f"No recent results found for '{query}'."

    # LangChain prompt \u2192 LLM \u2192 string output parser
    prompt = ChatPromptTemplate.from_messages([
        SystemMessage(content=(
            "You are a professional researcher. Write an accurate, engaging, "
            "human-like summary (~200 words) from the provided search results. "
            "Be factual and highlight key takeaways. No greetings."
        )),
        HumanMessage(content=(
            f"Topic: {query}\n\nSearch results:\n{source_info}\n\n"
            "Write the summary now."
        )),
    ])

    chain = prompt | _get_llm(MODEL_INSTANT, MAX_TOKENS_SUMMARY) | StrOutputParser()
    try:
        return chain.invoke({})
    except Exception as exc:
        print(f"[LLM] summary error: {exc}", file=sys.stderr)
        return source_info   # graceful fallback to raw snippets


# \u2500\u2500 Phase 2: Video-script generation \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\ndef generate_video_script(info_text: str) -> Optional[str]:
    """
    Convert a research summary into a short YouTube / Reels script (~100-120 words).
    Uses llama-3.3-70b-versatile for higher creative quality.
    """
    prompt = ChatPromptTemplate.from_messages([
        SystemMessage(content=(
            "You are a creative scriptwriter for YouTube Shorts and Instagram Reels. "
            "Write an engaging script with a strong hook and a clear call-to-action. "
            "Keep it to 100-120 words maximum."
        )),
        HumanMessage(content=f"Research summary:\n{info_text}\n\nWrite the video script now."),
    ])

    chain = prompt | _get_llm(MODEL_VERSATILE, MAX_TOKENS_SCRIPT) | StrOutputParser()
    try:
        return chain.invoke({})
    except Exception as exc:
        print(f"[LLM] script error: {exc}", file=sys.stderr)
        return None

app_src = '''
import os
import sys
from typing import Optional

# LangChain ≥ 1.2 imports (new-style: langchain-groq, langchain-core)
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from tavily import TavilyClient

# ── Model configuration ─────────────────────────────────────────────
# llama-3.1-8b-instant  : low latency, generous free-tier token allowance
# llama-3.3-70b-versatile: higher quality, used when deep reasoning is needed
MODEL_INSTANT    = "llama-3.1-8b-instant"
MODEL_VERSATILE  = "llama-3.3-70b-versatile"

# Token budgets chosen conservatively to stay within Groq free-tier limits.
MAX_TOKENS_SUMMARY = 512   # ~400 words output
MAX_TOKENS_SCRIPT  = 300   # ~120-word video script


def _get_llm(model: str, max_tokens: int) -> ChatGroq:
    """Initialise a ChatGroq LLM with the given model and token ceiling."""
    return ChatGroq(
        model=model,
        temperature=0.7,
        max_tokens=max_tokens,
        api_key=os.environ.get("GROQ_API_KEY"),
    )


def _get_tavily() -> TavilyClient:
    """Return a configured Tavily search client."""
    return TavilyClient(api_key=os.environ.get("TAVILY_API_KEY"))


# ── Phase 1: Real-time web research ────────────────────────────────
def get_realtime_info(query: str) -> Optional[str]:
    """
    Search the web with Tavily, then summarise results using LLaMA-instant.
    Returns a ~200-word human-readable summary or None on failure.
    """
    tavily = _get_tavily()

    try:
        resp = tavily.search(query=query, max_results=3, topic="general")
    except Exception as exc:
        print(f"[Tavily] search error: {exc}", file=sys.stderr)
        return None

    # Build a compact context string from search snippets.
    if resp and resp.get("results"):
        parts = []

        for r in resp["results"]:
            title = r.get("title", "")
            snippet = r.get("snippet") or r.get("content", "")[:300]
            url = r.get("url", "")

            parts.append(
                f"Title: {title}"
                f"\\nSnippet: {snippet}"
                f"\\nURL: {url}"
            )

        source_info = "\\n---\\n".join(parts)

    else:
        source_info = f"No recent results found for '{query}'."

    # LangChain prompt → LLM → string output parser
    prompt = ChatPromptTemplate.from_messages([
        SystemMessage(
            content=(
                "You are a professional researcher. Write an accurate, engaging, "
                "human-like summary (~200 words) from the provided search results. "
                "Be factual and highlight key takeaways. No greetings."
            )
        ),
        HumanMessage(
            content=(
                f"Topic: {query}\\n\\n"
                f"Search results:\\n{source_info}\\n\\n"
                "Write the summary now."
            )
        ),
    ])

    chain = prompt | _get_llm(MODEL_INSTANT, MAX_TOKENS_SUMMARY) | StrOutputParser()

    try:
        return chain.invoke({})
    except Exception as exc:
        print(f"[LLM] summary error: {exc}", file=sys.stderr)
        return source_info   # graceful fallback to raw snippets


# ── Phase 2: Video-script generation ───────────────────────────────
def generate_video_script(info_text: str) -> Optional[str]:
    """
    Convert a research summary into a short YouTube / Reels script (~100-120 words).
    Uses llama-3.3-70b-versatile for higher creative quality.
    """
    prompt = ChatPromptTemplate.from_messages([
        SystemMessage(
            content=(
                "You are a creative scriptwriter for YouTube Shorts and Instagram Reels. "
                "Write an engaging script with a strong hook and a clear call-to-action. "
                "Keep it to 100-120 words maximum."
            )
        ),
        HumanMessage(
            content=f"Research summary:\\n{info_text}\\n\\nWrite the video script now."
        ),
    ])

    chain = prompt | _get_llm(MODEL_VERSATILE, MAX_TOKENS_SCRIPT) | StrOutputParser()

    try:
        return chain.invoke({})
    except Exception as exc:
        print(f"[LLM] script error: {exc}", file=sys.stderr)
        return None
'''

with open("storyforge_agent/app.py", "w", encoding="utf-8") as f:
    f.write(app_src)

print("✅ app.py written successfully.")

"""## 🧪 Step 5 — Phase 1: Validate & Transform the Query"""

import sys
sys.path.insert(0, "storyforge_agent")

from utilities.query_validation_transformation import handle_query

# Define the topic you want to research (edit this freely).
TOPIC = "latest advancements in generative AI 2025"

# Validate and normalise the raw query string.
transformed = handle_query(TOPIC)
print("Query transformation result:")
for k, v in transformed.items():
    print(f"  {k:12s}: {v}")

# Use the cleaned query downstream for consistent results.
CLEAN_QUERY = transformed["cleaned"]
print(f"\nUsing cleaned query: '{CLEAN_QUERY}'")

"""## 🔍 Step 6 — Phase 2: Real-Time Web Research (Tavily → LLaMA)"""

from app import get_realtime_info
from utilities.logging_example import get_app_logger

logger = get_app_logger("storyforge.research")
logger.info("Starting real-time research for: %s", CLEAN_QUERY)

# Fetch and summarise web results — this calls Tavily + Groq.
summary = get_realtime_info(CLEAN_QUERY)

if summary:
    logger.info("Summary generated successfully (%d chars).", len(summary))
    print("\n📚 AI-Generated Research Summary")
    print("=" * 60)
    print(summary)
else:
    print("⚠️  Could not generate summary.")

"""## 🎬 Step 7 — Phase 3: Video Script Generation (LLaMA Versatile)"""

from app import generate_video_script

logger.info("Generating video script from summary.")

script = generate_video_script(summary) if summary else None

if script:
    logger.info("Script generated (%d chars).", len(script))
    print("\n🎥 Short Video Script")
    print("=" * 60)
    print(script)
else:
    print("⚠️  Could not generate video script.")

"""## 📋 Step 8 — Phase 4: Pydantic Request/Response Modelling"""

from utilities.pydantic_models import SearchRequest, build_search_response

# Build a validated request object for this search session.
request = SearchRequest(
    user_id="storyforge_colab",
    email="researcher@example.com",
    query=CLEAN_QUERY,
    tags=["ai", "youtube", "content-creation"],
)

response = build_search_response(request)

print("SearchRequest (validated):")
print(request.model_dump_json(indent=2))
print("\nSearchResponse (structured):")
print(response.model_dump_json(indent=2))

"""## 🧠 Step 9 — Phase 5: Mem0 Memory Layer (ChromaDB — free, local)"""

# Mem0 stores and retrieves contextual memory across sessions.
# Vector store: ChromaDB (runs locally, no paid cloud account needed).
# LLM: Groq llama-3.1-8b-instant (free tier).
# Embedder: HuggingFace multi-qa-MiniLM-L6-cos-v1 (runs locally).
try:
    from utilities.mem0_example import run_observability_demo
    run_observability_demo()
except Exception as e:
    print(f"⚠️  Mem0 demo skipped (optional): {e}")

"""## 📝 Step 10 — Phase 6: Logging Demo"""

from utilities.logging_example import run_logging_demo

# Run the structured logging demo — output goes to both stdout and
# storyforge_agent/outputs/storyforge.log
run_logging_demo()
print("\n✅ Log file saved to: storyforge_agent/outputs/storyforge.log")

"""## 💾 Step 11 — Save All Phase Outputs to Disk"""

import json
from datetime import datetime
from pathlib import Path

output_dir = Path("storyforge_agent/outputs")
output_dir.mkdir(parents=True, exist_ok=True)

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

# Save research summary
if summary:
    p = output_dir / f"phase2_summary_{timestamp}.txt"
    p.write_text(summary, encoding="utf-8")
    print(f"✅ Summary saved → {p}")

# Save video script
if script:
    p = output_dir / f"phase3_script_{timestamp}.txt"
    p.write_text(script, encoding="utf-8")
    print(f"✅ Script saved  → {p}")

# Save Pydantic models as JSON
models_data = {
    "request": json.loads(request.model_dump_json()),
    "response": json.loads(response.model_dump_json()),
}
p = output_dir / f"phase4_models_{timestamp}.json"
p.write_text(json.dumps(models_data, indent=2), encoding="utf-8")
print(f"✅ Models saved  → {p}")

# Save query transformation result
p = output_dir / f"phase1_query_{timestamp}.json"
p.write_text(json.dumps(transformed, indent=2), encoding="utf-8")
print(f"✅ Query saved   → {p}")

print("\nAll phase outputs saved.")

"""## 📦 Step 12 — Zip All Outputs for Download"""

import zipfile, os
from pathlib import Path

zip_path = "storyforge_outputs.zip"

# Collect every file under storyforge_agent/ (sources + outputs).
with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
    for fp in sorted(Path("storyforge_agent").rglob("*")):
        if fp.is_file() and "__pycache__" not in str(fp):
            zf.write(fp, arcname=str(fp))
            print(f"  + {fp}")

print(f"\n📦 ZIP created: {zip_path}")
print(f"   Size: {os.path.getsize(zip_path):,} bytes")

# Download the ZIP to your local machine.
try:
    from google.colab import files
    files.download("storyforge_outputs.zip")
    print("✅ Download triggered.")
except Exception:
    print("ℹ️  Not in Colab — find storyforge_outputs.zip in the working directory.")

"""## 🖥️ (Optional) Step 13 — Quick Smoke-Test of `app.py` Functions
> Directly exercises the same functions exposed by the Streamlit frontend.
"""

# Direct function test — equivalent to the Streamlit / Flask UI paths.
test_query = "OpenAI GPT-5 release news"

print(f"Testing app.py with query: '{test_query}'\n")

test_summary = get_realtime_info(test_query)
if test_summary:
    print("[Summary preview]")
    print(test_summary[:400], "...\n")

    test_script = generate_video_script(test_summary)
    if test_script:
        print("[Video script]")
        print(test_script)
else:
    print("No summary returned.")

"""---
## ✅ Notebook Complete
All phases ran successfully. Your ZIP contains:
- `storyforge_agent/app.py` — core pipeline (LangChain + Groq)
- `storyforge_agent/utilities/` — all utility modules
- `storyforge_agent/outputs/` — phase outputs (summary, script, JSON, logs)

"""