# -*- coding: utf-8 -*-
"""Agentic_RAG_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lm11mu1LNFJgLj8-iUfom5ccITZoP3DP

# 🤖 Agentic RAG System — Google Colab (v2)

**Architecture overview:**
- 📄 **Document Ingestion** — upload your PDF from local disk
- 🔍 **VectorStore** — FAISS + HuggingFace embeddings (free, no OpenAI key)
- 🧠 **LLM** — Groq `llama-3.3-70b-versatile` via `langchain-groq`
- 🔗 **LangGraph** — `retriever → agent (retriever tool + Wikipedia tool)` → answer
- 🌐 **Tool-calling** — Groq-compatible `bind_tools` + manual `ToolMessage` loop
- 🖥️ **Streamlit app** — run in Colab via `pyngrok` tunnel

> **Before running:** add `GROQ_API_KEY` in *Colab Secrets* (🔑 left sidebar → Secrets).

## 1 · Install dependencies
"""

# Pinned versions confirmed working with Groq + LangGraph on Colab
!pip install -q \
    langchain==0.3.27 \
    langchain-community==0.3.27 \
    langchain-groq \
    langchain-huggingface \
    langgraph==0.6.5 \
    faiss-cpu \
    pydantic \
    pypdf \
    wikipedia \
    sentence-transformers \
    beautifulsoup4 \
    requests \
    pyngrok \
    streamlit

import uuid  # keep in global scope — fixes langchain-core forward-ref NameError
print('✅ All packages installed successfully!')

"""## 2 · Load Groq API Key from Colab Secrets"""

import os
from google.colab import userdata

os.environ['GROQ_API_KEY'] = userdata.get('GROQ_API_KEY')
print('✅ GROQ_API_KEY loaded!')

"""## 3 · Configuration  (`src/config/config.py`)"""

import os
from langchain_groq import ChatGroq

class Config:
    """Configuration for the Agentic RAG system."""
    LLM_MODEL       = 'llama-3.1-8b-instant'
    EMBEDDING_MODEL = 'all-MiniLM-L6-v2'
    CHUNK_SIZE      = 500
    CHUNK_OVERLAP   = 50

    @classmethod
    def get_llm(cls):
        """Return a plain ChatGroq — tools bound separately per RAGNodes instance."""
        return ChatGroq(
            model=cls.LLM_MODEL,
            api_key=os.environ['GROQ_API_KEY'],
            temperature=0,
        )

print(f'✅ Config ready  |  LLM: {Config.LLM_MODEL}  |  Embeddings: {Config.EMBEDDING_MODEL}')

"""## 4 · RAG State  (`src/state/rag_state.py`)"""

from typing import List
from pydantic import BaseModel, ConfigDict
from langchain_core.documents import Document

class RAGState(BaseModel):
    """Typed state object flowing through the LangGraph pipeline."""
    question      : str
    retrieved_docs: List[Document] = []
    answer        : str = ''
    model_config = ConfigDict(arbitrary_types_allowed=True)

print('✅ RAGState defined')

"""## 5 · Document Processor  (`src/document_ingestion/document_processor.py`)"""

from typing import List, Union
from pathlib import Path
from langchain_community.document_loaders import PyPDFLoader, WebBaseLoader, TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

class DocumentProcessor:
    """Load documents from PDFs / URLs / TXT files and split into chunks."""

    def __init__(self, chunk_size: int = 500, chunk_overlap: int = 50):
        self.splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size, chunk_overlap=chunk_overlap
        )

    def load_from_pdf(self, file_path: Union[str, Path]) -> List[Document]:
        return PyPDFLoader(str(file_path)).load()

    def load_from_url(self, url: str) -> List[Document]:
        return WebBaseLoader(url).load()

    def load_from_txt(self, file_path: Union[str, Path]) -> List[Document]:
        return TextLoader(str(file_path), encoding='utf-8').load()

    def load_documents(self, sources: List[str]) -> List[Document]:
        docs: List[Document] = []
        for src in sources:
            src = src.strip()
            if src.startswith('http://') or src.startswith('https://'):
                print(f'  🌐 URL: {src}')
                docs.extend(self.load_from_url(src))
            else:
                path = Path(src)
                if path.suffix.lower() == '.pdf':
                    print(f'  📄 PDF: {path.name}')
                    docs.extend(self.load_from_pdf(path))
                elif path.suffix.lower() == '.txt':
                    print(f'  📝 TXT: {path.name}')
                    docs.extend(self.load_from_txt(path))
                else:
                    raise ValueError(f'Unsupported source: {src}')
        return docs

    def split_documents(self, documents: List[Document]) -> List[Document]:
        return self.splitter.split_documents(documents)

    def process(self, sources: List[str]) -> List[Document]:
        raw = self.load_documents(sources)
        chunks = self.split_documents(raw)
        print(f'  ✂️  {len(raw)} pages → {len(chunks)} chunks')
        return chunks

print('✅ DocumentProcessor defined')

"""## 6 · VectorStore  (`src/vectorstore/vectorstore.py`)"""

from typing import List
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document

class VectorStore:
    """FAISS vector store with local HuggingFace embeddings."""

    def __init__(self, model_name: str = Config.EMBEDDING_MODEL):
        print(f'  🔄 Loading embedding model: {model_name} …')
        self.embedding   = HuggingFaceEmbeddings(model_name=model_name)
        self.vectorstore = None
        self.retriever   = None
        print('  ✅ Embedding model loaded')

    def create_vectorstore(self, documents: List[Document]):
        print(f'  🔍 Embedding {len(documents)} chunks …')
        self.vectorstore = FAISS.from_documents(documents, self.embedding)
        self.retriever   = self.vectorstore.as_retriever(search_kwargs={'k': 6})
        print('  ✅ FAISS index created')

    def get_retriever(self):
        if self.retriever is None:
            raise ValueError('Call create_vectorstore() first.')
        return self.retriever

    def retrieve(self, query: str) -> List[Document]:
        return self.get_retriever().invoke(query)

print('✅ VectorStore defined')

"""## 7 · LangGraph Nodes  (`src/node/reactnode.py`)

**Groq-compatible tool-calling strategy** (no `create_react_agent`, no `AgentExecutor`):
1. Build `@tool`-decorated functions for document search and Wikipedia
2. Bind them to the LLM once with `llm.bind_tools(tools)`
3. In `generate_answer`, run a **manual loop**: call LLM → if `tool_calls` present → execute tools → append `ToolMessage` results → call LLM again
4. Stop when LLM returns a plain-text answer (no `tool_calls`) or `max_iterations` reached

"""

# src/node/reactnode.py  (inlined for Colab)
from typing import List, Optional
from langchain_core.documents import Document
from langchain_core.messages import (
    HumanMessage, SystemMessage, ToolMessage, AIMessage
)
from langchain_core.tools import tool


# ── Tool factory ──────────────────────────────────────────────────────────────
# Defined via factory so the retriever closure is captured cleanly.
# Using @tool decorator (not Tool()) avoids the uuid NameError in
# LangGraph's ToolNode type-hint inspection.

def _make_tools(retriever):
    """Return [search_documents, search_wikipedia] tools bound to retriever."""

    @tool
    def search_documents(query: str) -> str:
        """Search the uploaded PDF document for relevant passages. Always call this first."""
        docs: List[Document] = retriever.invoke(query)
        if not docs:
            return 'No relevant passages found in the document.'
        parts = []
        for i, d in enumerate(docs[:6], start=1):
            meta = d.metadata if hasattr(d, 'metadata') else {}
            page = meta.get('page', '?')
            src  = meta.get('source', meta.get('file_path', f'chunk_{i}'))
            parts.append(f'[{i}] (source={src}, page={page})\n{d.page_content}')
        return '\n\n'.join(parts)

    @tool
    def search_wikipedia(query: str) -> str:
        """Search Wikipedia for general background knowledge when the document lacks the answer."""
        from langchain_community.utilities import WikipediaAPIWrapper
        wrapper = WikipediaAPIWrapper(
            top_k_results=2, lang='en', doc_content_chars_max=2000
        )
        try:
            return wrapper.run(query)
        except Exception as e:
            return f'Wikipedia search failed: {e}'

    return [search_documents, search_wikipedia]


# ── RAGNodes ──────────────────────────────────────────────────────────────────
class RAGNodes:
    """Contains node functions for the LangGraph RAG workflow."""

    def __init__(self, retriever, llm, max_iterations: int = 5):
        self.retriever      = retriever
        self.llm            = llm
        self.max_iterations = max_iterations
        # Build tools and bind to LLM once at init time
        self._tools         = _make_tools(retriever)
        self._tool_map      = {t.name: t for t in self._tools}
        self._llm_with_tools = llm.bind_tools(self._tools)

    # ── Node 1: retrieve_docs ─────────────────────────────────────────────────
    def retrieve_docs(self, state: RAGState) -> RAGState:
        """Pre-fetch top-k docs so state.retrieved_docs is always populated."""
        docs = self.retriever.invoke(state.question)
        return RAGState(question=state.question, retrieved_docs=docs)

    # ── Node 2: generate_answer ───────────────────────────────────────────────
    def generate_answer(self, state: RAGState) -> RAGState:
        """
        Groq-compatible agentic tool loop.
        Uses bind_tools + manual ToolMessage loop instead of create_react_agent,
        which avoids the Groq BadRequestError (tool_use_failed).
        """
        system = SystemMessage(content=(
            'You are a helpful RAG assistant. '
            'Use search_documents first to find information from the uploaded PDF. '
            'Use search_wikipedia only if the document does not contain enough information. '
            'After gathering information, provide a clear, concise final answer.'
        ))
        messages = [system, HumanMessage(content=state.question)]
        response: Optional[AIMessage] = None

        for _ in range(self.max_iterations):
            response = self._llm_with_tools.invoke(messages)
            messages.append(response)

            # No tool calls → LLM has produced a final answer
            if not getattr(response, 'tool_calls', None):
                break

            # Execute each requested tool and feed results back as ToolMessages
            for tc in response.tool_calls:
                name   = tc['name']
                args   = tc['args']
                tid    = tc['id']
                if name in self._tool_map:
                    try:
                        result = self._tool_map[name].invoke(args)
                    except Exception as e:
                        result = f'Tool error: {e}'
                else:
                    result = f'Unknown tool: {name}'
                messages.append(ToolMessage(content=str(result), tool_call_id=tid))
        else:
            # Reached max_iterations — force a final answer
            response = self._llm_with_tools.invoke(
                messages + [HumanMessage(content='Please provide your final answer now.')]
            )

        answer = response.content if response else 'Could not generate an answer.'
        return RAGState(
            question=state.question,
            retrieved_docs=state.retrieved_docs,
            answer=answer,
        )

print('✅ RAGNodes defined  (src/node/reactnode.py)')
print('   Tools: search_documents + search_wikipedia')
print('   Loop : bind_tools + manual ToolMessage loop (Groq-safe)')

"""## 8 · Graph Builder  (`src/graph_builder/graph_builder.py`)"""

from langgraph.graph import StateGraph, END

class GraphBuilder:
    """Assembles and compiles the LangGraph RAG workflow."""

    def __init__(self, retriever, llm):
        self.nodes = RAGNodes(retriever, llm)
        self.graph = None

    def build(self):
        builder = StateGraph(RAGState)
        builder.add_node('retriever', self.nodes.retrieve_docs)
        builder.add_node('responder', self.nodes.generate_answer)
        builder.set_entry_point('retriever')
        builder.add_edge('retriever', 'responder')
        builder.add_edge('responder', END)
        self.graph = builder.compile()
        print('✅ LangGraph compiled  →  retriever ➜ responder ➜ END')
        return self.graph

    def run(self, question: str) -> dict:
        if self.graph is None:
            self.build()
        return self.graph.invoke(RAGState(question=question))

print('✅ GraphBuilder defined')

"""## 9 · Upload your PDF from local disk

Run the cell — a file picker will appear. Select your PDF and wait for the upload.
"""

from google.colab import files
import os

print('📂 Please select your PDF file …')
uploaded     = files.upload()
pdf_filename = list(uploaded.keys())[0]
PDF_PATH     = os.path.abspath(pdf_filename)

print(f'\n✅ Uploaded : {pdf_filename}  ({len(uploaded[pdf_filename]):,} bytes)')
print(f'   Saved to : {PDF_PATH}')

"""## 10 · Initialise the full RAG pipeline"""

import time

print('🚀 Initialising Agentic RAG System …\n')

llm = Config.get_llm()
print(f'✅ LLM ready: {Config.LLM_MODEL} (Groq)\n')

print('📄 Loading & chunking PDF …')
doc_processor = DocumentProcessor(
    chunk_size=Config.CHUNK_SIZE, chunk_overlap=Config.CHUNK_OVERLAP
)
documents = doc_processor.process([PDF_PATH])
print(f'   Total chunks: {len(documents)}\n')

print('🔍 Building FAISS vector store …')
vector_store = VectorStore()
vector_store.create_vectorstore(documents)
print()

print('🔗 Building LangGraph …')
graph_builder = GraphBuilder(
    retriever=vector_store.get_retriever(),
    llm=llm,
)
graph_builder.build()
print('\n🎉 System ready — start asking questions!')

"""## 11 · Ask a single question"""

import time

question = 'What is attention mechanism?'  # ← edit this

print(f'❓ Question: {question}\n')
t0      = time.time()
result  = graph_builder.run(question)
elapsed = time.time() - t0

print(f'\n💡 Answer:\n{result["answer"]}')
print(f'\n⏱️  {elapsed:.2f}s  |  {len(result["retrieved_docs"])} docs retrieved')

"""## 12 · Inspect retrieved source passages"""

for i, doc in enumerate(result['retrieved_docs'], start=1):
    meta   = doc.metadata
    source = meta.get('source', meta.get('file_path', 'unknown'))
    page   = meta.get('page', '?')
    print(f'--- Doc {i} | source: {source} | page: {page} ---')
    print(doc.page_content[:400])
    print()

"""## 13 · Interactive Q&A loop

Type questions one at a time. Enter `quit` to stop.
"""

import time

print('💬 Interactive Mode — type "quit" to stop\n')
print('─' * 60)

while True:
    try:
        q = input('\nYour question: ').strip()
    except EOFError:
        break
    if not q:
        continue
    if q.lower() in ('quit', 'exit', 'q'):
        print('👋 Goodbye!')
        break
    t0     = time.time()
    result = graph_builder.run(q)
    print(f'\n💡 Answer:\n{result["answer"]}')
    print(f'\n⏱️  {time.time()-t0:.2f}s  |  {len(result["retrieved_docs"])} docs retrieved')
    print('─' * 60)

"""## 14 · Batch questions (optional)"""

import time

BATCH_QUESTIONS = [
    'What is the main contribution of this paper?',
    'What methods or techniques are described?',
    'What are the key findings or results?',
]

print('=' * 60)
print('📝 Batch Q&A')
print('=' * 60)

for bq in BATCH_QUESTIONS:
    print(f'\n❓ {bq}')
    t0  = time.time()
    res = graph_builder.run(bq)
    print(f'💡 {res["answer"]}')
    print(f'   ⏱️  {time.time()-t0:.2f}s')
    print('-' * 60)

"""---
## 15 · Streamlit App  (`streamlit_app.py`)

The cells below write the Streamlit app to disk and launch it with `pyngrok`.  
A public URL will appear — open it to use the full chat UI.

> The Streamlit app is self-contained: it re-initialises its own RAG pipeline  
> internally (same architecture — PDF upload via sidebar, Groq LLM, FAISS, LangGraph).

### 15a · Write `streamlit_app.py` to disk
"""

st_source = [
    'import os, time, uuid\n',
    'import streamlit as st\n',
    'from typing import List\n',
    'from pydantic import BaseModel, ConfigDict\n',
    'from langchain_groq import ChatGroq\n',
    'from langchain_community.document_loaders import PyPDFLoader\n',
    'from langchain_text_splitters import RecursiveCharacterTextSplitter\n',
    'from langchain_community.vectorstores import FAISS\n',
    'from langchain_huggingface import HuggingFaceEmbeddings\n',
    'from langchain_core.documents import Document\n',
    'from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage, AIMessage\n',
    'from langchain_core.tools import tool\n',
    'from langgraph.graph import StateGraph, END\n',
    '\n',
    '# ── constants ────────────────────────────────────────────────────────────────\n',
    "GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')\n",
    "LLM_MODEL    = 'llama-3.3-70b-versatile'\n",
    "EMBED_MODEL  = 'all-MiniLM-L6-v2'\n",
    '\n',
    '# ── page config ───────────────────────────────────────────────────────────────\n',
    "st.set_page_config(page_title='Agentic RAG', page_icon='🤖', layout='centered')\n",
    "st.title('🤖 Agentic RAG — PDF Q&A')\n",
    "st.caption('Powered by Groq · LangGraph · FAISS · HuggingFace Embeddings')\n",
    '\n',
    '# ── RAGState ──────────────────────────────────────────────────────────────────\n',
    'class RAGState(BaseModel):\n',
    '    question      : str\n',
    '    retrieved_docs: List[Document] = []\n',
    "    answer        : str = ''\n",
    '    model_config = ConfigDict(arbitrary_types_allowed=True)\n',
    '\n',
    '# ── tool factory ─────────────────────────────────────────────────────────────\n',
    'def _make_tools(retriever):\n',
    '    @tool\n',
    '    def search_documents(query: str) -> str:\n',
    "        'Search the uploaded PDF document for relevant passages. Always call this first.'\n",
    '        docs = retriever.invoke(query)\n',
    '        if not docs:\n',
    "            return 'No relevant passages found.'\n",
    '        parts = []\n',
    '        for i, d in enumerate(docs[:6], 1):\n',
    "            meta = d.metadata if hasattr(d, 'metadata') else {}\n",
    "            page = meta.get('page', '?')\n",
    "            parts.append(f'[{i}] (page={page})\\n{d.page_content}')\n",
    "        return '\\n\\n'.join(parts)\n",
    '\n',
    '    @tool\n',
    '    def search_wikipedia(query: str) -> str:\n',
    "        'Search Wikipedia for general knowledge when the document lacks the answer.'\n",
    '        from langchain_community.utilities import WikipediaAPIWrapper\n',
    "        wrapper = WikipediaAPIWrapper(top_k_results=2, lang='en', doc_content_chars_max=2000)\n",
    '        try:\n',
    '            return wrapper.run(query)\n',
    '        except Exception as e:\n',
    "            return f'Wikipedia error: {e}'\n",
    '\n',
    '    return [search_documents, search_wikipedia]\n',
    '\n',
    '# ── agentic loop ─────────────────────────────────────────────────────────────\n',
    'def run_agent(question, llm_with_tools, tool_map, max_iter=5):\n',
    '    system   = SystemMessage(content=(\n',
    "        'You are a helpful RAG assistant. '\n",
    "        'Use search_documents first, then search_wikipedia if needed. '\n",
    "        'Give a clear final answer.'\n",
    '    ))\n',
    '    messages = [system, HumanMessage(content=question)]\n',
    '    response = None\n',
    '    for _ in range(max_iter):\n',
    '        response = llm_with_tools.invoke(messages)\n',
    '        messages.append(response)\n',
    "        if not getattr(response, 'tool_calls', None):\n",
    '            break\n',
    '        for tc in response.tool_calls:\n',
    "            name, args, tid = tc['name'], tc['args'], tc['id']\n",
    "            result = tool_map[name].invoke(args) if name in tool_map else f'Unknown tool: {name}'\n",
    '            messages.append(ToolMessage(content=str(result), tool_call_id=tid))\n',
    "    return response.content if response else 'No answer generated.'\n",
    '\n',
    '# ── cached pipeline init ──────────────────────────────────────────────────────\n',
    '@st.cache_resource\n',
    'def init_pipeline(pdf_bytes, filename):\n',
    "    tmp = f'/tmp/{filename}'\n",
    "    with open(tmp, 'wb') as f:\n",
    '        f.write(pdf_bytes)\n',
    '    pages  = PyPDFLoader(tmp).load()\n',
    '    chunks = RecursiveCharacterTextSplitter(\n',
    '        chunk_size=500, chunk_overlap=50\n',
    '    ).split_documents(pages)\n',
    '    embed = HuggingFaceEmbeddings(model_name=EMBED_MODEL)\n',
    '    vs    = FAISS.from_documents(chunks, embed)\n',
    "    ret   = vs.as_retriever(search_kwargs={'k': 6})\n",
    '    llm   = ChatGroq(model=LLM_MODEL, api_key=GROQ_API_KEY, temperature=0)\n',
    '    tools = _make_tools(ret)\n',
    '    llm_t = llm.bind_tools(tools)\n',
    '    t_map = {t.name: t for t in tools}\n',
    '    return llm_t, t_map, len(chunks)\n',
    '\n',
    '# ── sidebar ───────────────────────────────────────────────────────────────────\n',
    'with st.sidebar:\n',
    "    st.header('📄 Upload PDF')\n",
    "    uploaded_file = st.file_uploader('Choose a PDF', type='pdf')\n",
    "    st.markdown('---')\n",
    "    st.caption(f'Model: {LLM_MODEL}')\n",
    "    st.caption(f'Embeddings: {EMBED_MODEL}')\n",
    '\n',
    'if not uploaded_file:\n',
    "    st.info('👈 Upload a PDF from the sidebar to get started.')\n",
    '    st.stop()\n',
    '\n',
    "with st.spinner('🔄 Initialising pipeline (first run ~30s) …'):\n",
    '    llm_with_tools, tool_map, n_chunks = init_pipeline(\n',
    '        uploaded_file.read(), uploaded_file.name\n',
    '    )\n',
    "st.success(f'✅ Ready — {n_chunks} chunks indexed from **{uploaded_file.name}**')\n",
    '\n',
    '# ── chat history ──────────────────────────────────────────────────────────────\n',
    "if 'history' not in st.session_state:\n",
    '    st.session_state.history = []\n',
    '\n',
    'for turn in st.session_state.history:\n',
    "    with st.chat_message('user'):\n",
    "        st.write(turn['q'])\n",
    "    with st.chat_message('assistant'):\n",
    "        st.write(turn['a'])\n",
    '        st.caption(f"⏱️ {turn[\'t\']:.2f}s")\n',
    '\n',
    '# ── chat input ────────────────────────────────────────────────────────────────\n',
    "question = st.chat_input('Ask a question about your PDF …')\n",
    'if question:\n',
    "    with st.chat_message('user'):\n",
    '        st.write(question)\n',
    "    with st.chat_message('assistant'):\n",
    "        with st.spinner('🤔 Thinking …'):\n",
    '            t0      = time.time()\n',
    '            answer  = run_agent(question, llm_with_tools, tool_map)\n',
    '            elapsed = time.time() - t0\n',
    '        st.write(answer)\n',
    "        st.caption(f'⏱️ {elapsed:.2f}s')\n",
    "    st.session_state.history.append({'q': question, 'a': answer, 't': elapsed})\n",
]
with open('streamlit_app.py', 'w') as f:
    f.writelines(st_source)
print('✅ streamlit_app.py written (%d lines)' % len(st_source))

"""### 15b · Launch Streamlit with pyngrok

A public URL will appear below — open it in a new browser tab.
"""

import subprocess, time, os
from pyngrok import ngrok

# Kill any previous instance
os.system('pkill -f streamlit 2>/dev/null; sleep 1')

# Optional: set ngrok auth token to remove session limits
from google.colab import userdata
ngrok.set_auth_token(userdata.get('NGROK_AUTHTOKEN'))

# Launch Streamlit in background
proc = subprocess.Popen(
    ['streamlit', 'run', 'streamlit_app.py',
     '--server.port', '8501',
     '--server.headless', 'true',
     '--server.enableCORS', 'false',
     '--server.enableXsrfProtection', 'false'],
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
)
time.sleep(4)  # wait for Streamlit to start

public_url = ngrok.connect(8501)
print('\n' + '=' * 60)
print('🚀 Streamlit is running!')
print(f'🌐 Open in browser: {public_url}')
print('=' * 60)
print('\n   Upload your PDF in the sidebar and start chatting.')
print('   Run the cell below to stop the server.')

"""### 15c · Stop Streamlit server"""

from pyngrok import ngrok
import os

ngrok.kill()
os.system('pkill -f streamlit 2>/dev/null')
print('✅ Streamlit server stopped')